"""E2R archetype definitions.

Archetypes describe business-model patterns, not individual stocks. They are
used for taxonomy, case-library coverage, and later score-weight design.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Mapping


class E2RArchetype(str, Enum):
    """Canonical E2R sector/business archetypes."""

    CONTRACT_BACKLOG_INDUSTRIAL = "CONTRACT_BACKLOG_INDUSTRIAL"
    GRID_TRANSFORMER_SHORTAGE = "GRID_TRANSFORMER_SHORTAGE"
    GRID_TRANSFORMER_SHORTAGE_KOREA = "GRID_TRANSFORMER_SHORTAGE_KOREA"
    GRID_TRANSFORMER_MIDCAP_KOREA = "GRID_TRANSFORMER_MIDCAP_KOREA"
    POWER_CABLE_GRID_BACKLOG_KOREA = "POWER_CABLE_GRID_BACKLOG_KOREA"
    GRID_US_LOCALIZATION_CAPA = "GRID_US_LOCALIZATION_CAPA"
    GRID_EHV_TRANSFORMER_EXPORT = "GRID_EHV_TRANSFORMER_EXPORT"
    GRID_MEDIUM_VOLTAGE_EXPANSION = "GRID_MEDIUM_VOLTAGE_EXPANSION"
    GRID_SUPPLY_SLOT_PREBUY = "GRID_SUPPLY_SLOT_PREBUY"
    AI_DATA_CENTER_POWER_EQUIPMENT = "AI_DATA_CENTER_POWER_EQUIPMENT"
    GAS_TURBINE_POWER_BACKLOG = "GAS_TURBINE_POWER_BACKLOG"
    POWER_EQUIPMENT_BACKLOG_TO_FCF = "POWER_EQUIPMENT_BACKLOG_TO_FCF"
    POWER_EQUIPMENT_BACKLOG_TO_FCF_KOREA = "POWER_EQUIPMENT_BACKLOG_TO_FCF_KOREA"
    POWER_EQUIPMENT_CAPITAL_RETURN = "POWER_EQUIPMENT_CAPITAL_RETURN"
    DATA_CENTER_GRID_FLEXIBILITY_OVERLAY = "DATA_CENTER_GRID_FLEXIBILITY_OVERLAY"
    DEFENSE_GOVERNMENT_BACKLOG = "DEFENSE_GOVERNMENT_BACKLOG"
    DEFENSE_ELECTRONICS_KF21_RADAR = "DEFENSE_ELECTRONICS_KF21_RADAR"
    SPACE_LAUNCH_PROGRAM_OF_RECORD = "SPACE_LAUNCH_PROGRAM_OF_RECORD"
    DEFENSE_CAPITAL_RAISE_DILUTION = "DEFENSE_CAPITAL_RAISE_DILUTION"
    DEFENSE_AIRCRAFT_EXPORT_BACKLOG = "DEFENSE_AIRCRAFT_EXPORT_BACKLOG"
    DEFENSE_INTERCEPTOR_COMBAT_VALIDATION = "DEFENSE_INTERCEPTOR_COMBAT_VALIDATION"
    DEFENSE_LOCAL_PRODUCTION_PLATFORM = "DEFENSE_LOCAL_PRODUCTION_PLATFORM"
    DEFENSE_CAPITAL_ALLOCATION_SHOCK = "DEFENSE_CAPITAL_ALLOCATION_SHOCK"
    DEFENSE_US_SHIPBUILDING_PLATFORM = "DEFENSE_US_SHIPBUILDING_PLATFORM"
    DEFENSE_UNMANNED_NAVAL_SYSTEMS = "DEFENSE_UNMANNED_NAVAL_SYSTEMS"
    DEFENSE_TECH_AUTONOMOUS_SYSTEMS = "DEFENSE_TECH_AUTONOMOUS_SYSTEMS"
    DEFENSE_DRONE_COUNTER_UAS = "DEFENSE_DRONE_COUNTER_UAS"
    DEFENSE_AI_SOFTWARE_INTELLIGENCE = "DEFENSE_AI_SOFTWARE_INTELLIGENCE"
    SHIPBUILDING_OFFSHORE_BACKLOG = "SHIPBUILDING_OFFSHORE_BACKLOG"
    SHIPBUILDING_EQUIPMENT_BACKLOG_KOREA = "SHIPBUILDING_EQUIPMENT_BACKLOG_KOREA"
    SHIPBUILDING_US_PLATFORM_RESTRUCTURING = "SHIPBUILDING_US_PLATFORM_RESTRUCTURING"
    SHIP_MRO_RECURRING_PLATFORM = "SHIP_MRO_RECURRING_PLATFORM"
    GEOPOLITICAL_SHIPBUILDING_SANCTION_OVERLAY = "GEOPOLITICAL_SHIPBUILDING_SANCTION_OVERLAY"
    MOU_LOI_NOT_CONTRACT = "MOU_LOI_NOT_CONTRACT"
    SHIPBUILDING_NAVAL_MRO = "SHIPBUILDING_NAVAL_MRO"
    SHIPBUILDING_PROCUREMENT_LEADTIME = "SHIPBUILDING_PROCUREMENT_LEADTIME"
    RAIL_INFRASTRUCTURE = "RAIL_INFRASTRUCTURE"
    CONSTRUCTION_EQUIPMENT_CYCLE_KOREA = "CONSTRUCTION_EQUIPMENT_CYCLE_KOREA"
    CONSTRUCTION_EQUIPMENT_GOVERNANCE_OVERLAY = "CONSTRUCTION_EQUIPMENT_GOVERNANCE_OVERLAY"
    NUCLEAR_EXISTING_PPA = "NUCLEAR_EXISTING_PPA"
    NUCLEAR_EXISTING_PPA_RESTART = "NUCLEAR_EXISTING_PPA_RESTART"
    NUCLEAR_EXPORT_PREFERRED_BIDDER = "NUCLEAR_EXPORT_PREFERRED_BIDDER"
    NUCLEAR_EXPORT_LEGAL_GATE = "NUCLEAR_EXPORT_LEGAL_GATE"
    NUCLEAR_DECOMMISSIONING_KOREA = "NUCLEAR_DECOMMISSIONING_KOREA"
    NUCLEAR_POLICY_STAGE1_2_NOT_GREEN = "NUCLEAR_POLICY_STAGE1_2_NOT_GREEN"
    NUCLEAR_GRID_INJECTION_RIGHTS = "NUCLEAR_GRID_INJECTION_RIGHTS"
    SPACE_SATELLITE_CAPITAL_ALLOCATION_RISK = "SPACE_SATELLITE_CAPITAL_ALLOCATION_RISK"
    PROJECT_DELAY_CAPEX_OVERLAY = "PROJECT_DELAY_CAPEX_OVERLAY"
    DATA_CENTER_GRID_PERMITTING_OVERLAY = "DATA_CENTER_GRID_PERMITTING_OVERLAY"
    CAPITAL_ALLOCATION_DILUTION_OVERLAY = "CAPITAL_ALLOCATION_DILUTION_OVERLAY"
    SMART_FACTORY_AUTOMATION = "SMART_FACTORY_AUTOMATION"
    EXPORT_RECURRING_CONSUMER = "EXPORT_RECURRING_CONSUMER"
    K_BEAUTY_EXPORT_DISTRIBUTION = "K_BEAUTY_EXPORT_DISTRIBUTION"
    MEMORY_HBM_CAPACITY = "MEMORY_HBM_CAPACITY"
    MEMORY_HBM_LTA_PREPAYMENT = "MEMORY_HBM_LTA_PREPAYMENT"
    HBM_CATCHUP_EXECUTION = "HBM_CATCHUP_EXECUTION"
    HBM_CATCHUP_EXECUTION_RISK = "HBM_CATCHUP_EXECUTION_RISK"
    MEMORY_SUPPLY_REALLOCATION = "MEMORY_SUPPLY_REALLOCATION"
    AI_STORAGE_NAND_SHORTAGE = "AI_STORAGE_NAND_SHORTAGE"
    COMMODITY_MEMORY_GENERAL_SEMI = "COMMODITY_MEMORY_GENERAL_SEMI"
    SEMI_EQUIPMENT_CAPEX = "SEMI_EQUIPMENT_CAPEX"
    SEMI_EQUIPMENT_AI_CAPEX = "SEMI_EQUIPMENT_AI_CAPEX"
    HBM_BONDER_EQUIPMENT_KOREA = "HBM_BONDER_EQUIPMENT_KOREA"
    ADVANCED_PACKAGING_EQUIPMENT_KOREA = "ADVANCED_PACKAGING_EQUIPMENT_KOREA"
    AI_SERVER_PCB_MLB_KOREA = "AI_SERVER_PCB_MLB_KOREA"
    SEMICONDUCTOR_TEST_SOCKET_KOREA = "SEMICONDUCTOR_TEST_SOCKET_KOREA"
    HBM_TEST_EQUIPMENT_KOREA = "HBM_TEST_EQUIPMENT_KOREA"
    GLASS_SUBSTRATE_ADVANCED_PACKAGING_KOREA = "GLASS_SUBSTRATE_ADVANCED_PACKAGING_KOREA"
    SYSTEM_SEMI_DESIGN_HOUSE_AI_ORDER = "SYSTEM_SEMI_DESIGN_HOUSE_AI_ORDER"
    ADVANCED_PACKAGING_EQUIPMENT_BASKET = "ADVANCED_PACKAGING_EQUIPMENT_BASKET"
    AI_SERVER_PCB_SUBSTRATE_SECOND_WAVE = "AI_SERVER_PCB_SUBSTRATE_SECOND_WAVE"
    MLCC_AI_SERVER_COMPONENTS = "MLCC_AI_SERVER_COMPONENTS"
    CAMERA_LIDAR_ADAS_ELECTRONICS = "CAMERA_LIDAR_ADAS_ELECTRONICS"
    ON_DEVICE_AI_THEME_KOREA = "ON_DEVICE_AI_THEME_KOREA"
    SEMI_CAPEX_ORDER_TO_REVENUE = "SEMI_CAPEX_ORDER_TO_REVENUE"
    IP_LEAK_SUPPLY_CHAIN_REDTEAM = "IP_LEAK_SUPPLY_CHAIN_REDTEAM"
    LABOR_PRODUCTION_DISRUPTION_OVERLAY = "LABOR_PRODUCTION_DISRUPTION_OVERLAY"
    SYSTEM_SEMI_FOUNDARY_OPTION_KOREA = "SYSTEM_SEMI_FOUNDARY_OPTION_KOREA"
    AI_CHIP_FABRIC_PRIVATE_RELATED = "AI_CHIP_FABRIC_PRIVATE_RELATED"
    ON_DEVICE_AI_THEME = "ON_DEVICE_AI_THEME"
    MOU_OR_REPORT_NOT_CONTRACT = "MOU_OR_REPORT_NOT_CONTRACT"
    HBM_SUPPLY_CHAIN_LABOR_DISRUPTION_OVERLAY = "HBM_SUPPLY_CHAIN_LABOR_DISRUPTION_OVERLAY"
    AI_CHIP_LISTED_EARNINGS_LINK_GATE = "AI_CHIP_LISTED_EARNINGS_LINK_GATE"
    SEMI_MATERIALS_PROCESS = "SEMI_MATERIALS_PROCESS"
    CUSTOM_AI_ASIC_HYPERSCALER = "CUSTOM_AI_ASIC_HYPERSCALER"
    CUSTOM_AI_ASIC_MARGIN_CONCENTRATION = "CUSTOM_AI_ASIC_MARGIN_CONCENTRATION"
    ADVANCED_PACKAGING_PCB = "ADVANCED_PACKAGING_PCB"
    ADVANCED_PACKAGING_COWOS_EMIB = "ADVANCED_PACKAGING_COWOS_EMIB"
    AI_NETWORKING_SWITCHING_INFRA = "AI_NETWORKING_SWITCHING_INFRA"
    PHOTONICS_AI_DATACENTER_CHIPS = "PHOTONICS_AI_DATACENTER_CHIPS"
    DISPLAY_OLED_SUPPLYCHAIN = "DISPLAY_OLED_SUPPLYCHAIN"
    ELECTRONIC_COMPONENTS_MLCC_SENSOR = "ELECTRONIC_COMPONENTS_MLCC_SENSOR"
    AI_CHIP_FABRIC_INFRA = "AI_CHIP_FABRIC_INFRA"
    AI_ACCELERATOR_CHIP_PUREPLAY = "AI_ACCELERATOR_CHIP_PUREPLAY"
    AI_SERVER_ODM_EMS_SUPPLY_CHAIN = "AI_SERVER_ODM_EMS_SUPPLY_CHAIN"
    NEOCLOUD_GPU_RENTAL = "NEOCLOUD_GPU_RENTAL"
    OPTICAL_NETWORKING_AI_DATACENTER = "OPTICAL_NETWORKING_AI_DATACENTER"
    INDUSTRIAL_GASES_SEMICONDUCTOR_INFRA = "INDUSTRIAL_GASES_SEMICONDUCTOR_INFRA"
    AI_DATA_CENTER_COOLING = "AI_DATA_CENTER_COOLING"
    AI_GRID_FLEXIBILITY_SOFTWARE = "AI_GRID_FLEXIBILITY_SOFTWARE"
    BATTERY_MATERIALS_CAPEX_OVERHEAT = "BATTERY_MATERIALS_CAPEX_OVERHEAT"
    BATTERY_MATERIALS_CAPEX_OVERHEAT_KOREA = "BATTERY_MATERIALS_CAPEX_OVERHEAT_KOREA"
    BATTERY_EQUIPMENT_PARTS = "BATTERY_EQUIPMENT_PARTS"
    BATTERY_RECYCLING_ESS_SHIFT = "BATTERY_RECYCLING_ESS_SHIFT"
    ESS_LFP_GRID_STORAGE = "ESS_LFP_GRID_STORAGE"
    ESS_LFP_GRID_STORAGE_KOREA = "ESS_LFP_GRID_STORAGE_KOREA"
    ESS_TESLA_MEGAPACK_SUPPLY_CHAIN = "ESS_TESLA_MEGAPACK_SUPPLY_CHAIN"
    ESS_AI_DATA_CENTER_STORAGE = "ESS_AI_DATA_CENTER_STORAGE"
    EV_TO_ESS_CAPACITY_REDEPLOYMENT = "EV_TO_ESS_CAPACITY_REDEPLOYMENT"
    EV_TO_ESS_CAPACITY_REDEPLOYMENT_KOREA = "EV_TO_ESS_CAPACITY_REDEPLOYMENT_KOREA"
    EV_BATTERY_JV_RESTRUCTURING = "EV_BATTERY_JV_RESTRUCTURING"
    EV_CAPA_CONTRACT_CANCELLATION = "EV_CAPA_CONTRACT_CANCELLATION"
    BATTERY_CONTRACT_CANCELLATION_4C = "BATTERY_CONTRACT_CANCELLATION_4C"
    BATTERY_TAX_CREDIT_QUALITY_OVERLAY = "BATTERY_TAX_CREDIT_QUALITY_OVERLAY"
    CONTRACT_CANCELLATION_CUSTOMER_STRATEGY_RISK = "CONTRACT_CANCELLATION_CUSTOMER_STRATEGY_RISK"
    BATTERY_CONTRACT_DISCLOSURE_CONFIDENCE = "BATTERY_CONTRACT_DISCLOSURE_CONFIDENCE"
    SECOND_LIFE_BATTERY_GRID_STORAGE = "SECOND_LIFE_BATTERY_GRID_STORAGE"
    EV_INFRASTRUCTURE = "EV_INFRASTRUCTURE"
    HYDROGEN_FUEL_CELL_INFRA = "HYDROGEN_FUEL_CELL_INFRA"
    SOLAR_TARIFF_SUPPLYCHAIN = "SOLAR_TARIFF_SUPPLYCHAIN"
    RENEWABLE_ENERGY_POLICY = "RENEWABLE_ENERGY_POLICY"
    RENEWABLE_ENERGY_PROJECT_ECONOMICS = "RENEWABLE_ENERGY_PROJECT_ECONOMICS"
    ENERGY_DISTRIBUTION_FUEL = "ENERGY_DISTRIBUTION_FUEL"
    WASTE_RECYCLING_ENVIRONMENT = "WASTE_RECYCLING_ENVIRONMENT"
    CARBON_CREDIT_CBAM_COMPLIANCE = "CARBON_CREDIT_CBAM_COMPLIANCE"
    DATA_CENTER_WATER_REUSE_INFRA = "DATA_CENTER_WATER_REUSE_INFRA"
    EV_FIRE_RISK_OVERLAY = "EV_FIRE_RISK_OVERLAY"
    EV_FIRE_BESS_SAFETY_OVERLAY = "EV_FIRE_BESS_SAFETY_OVERLAY"
    BESS_SAFETY_PERMITTING = "BESS_SAFETY_PERMITTING"
    BATTERY_HEALTH_TRANSPARENCY_OVERLAY = "BATTERY_HEALTH_TRANSPARENCY_OVERLAY"
    BATTERY_SOH_SECOND_LIFE_TRANSPARENCY = "BATTERY_SOH_SECOND_LIFE_TRANSPARENCY"
    BATTERY_GRAPHITE_SUPPLYCHAIN_SECURITY = "BATTERY_GRAPHITE_SUPPLYCHAIN_SECURITY"
    ANODE_GRAPHITE_SUPPLYCHAIN_KOREA = "ANODE_GRAPHITE_SUPPLYCHAIN_KOREA"
    CATHODE_LONG_CONTRACT_VISIBILITY = "CATHODE_LONG_CONTRACT_VISIBILITY"
    LITHIUM_RESOURCE_SECURITY_KOREA = "LITHIUM_RESOURCE_SECURITY_KOREA"
    SEPARATOR_EV_DEMAND_CYCLE = "SEPARATOR_EV_DEMAND_CYCLE"
    COPPER_FOIL_EV_DEMAND_CYCLE = "COPPER_FOIL_EV_DEMAND_CYCLE"
    ELECTROLYTE_CAPA_SUPPLYCHAIN = "ELECTROLYTE_CAPA_SUPPLYCHAIN"
    BATTERY_EQUIPMENT_CAPEX_CYCLE = "BATTERY_EQUIPMENT_CAPEX_CYCLE"
    BATTERY_RECYCLING_UNIT_ECONOMICS = "BATTERY_RECYCLING_UNIT_ECONOMICS"
    SILICON_ANODE_COMMERCIALIZATION = "SILICON_ANODE_COMMERCIALIZATION"
    EVENT_LITHIUM_PRICE_RALLY = "EVENT_LITHIUM_PRICE_RALLY"
    LITHIUM_CYCLE_OVERLAY = "LITHIUM_CYCLE_OVERLAY"
    LITHIUM_ESS_DEMAND_CYCLE = "LITHIUM_ESS_DEMAND_CYCLE"
    SODIUM_ION_SUBSTITUTION_OVERLAY = "SODIUM_ION_SUBSTITUTION_OVERLAY"
    SODIUM_ION_NEXTGEN_MATERIALS = "SODIUM_ION_NEXTGEN_MATERIALS"
    SOLID_STATE_COMMERCIALIZATION_LICENSE = "SOLID_STATE_COMMERCIALIZATION_LICENSE"
    SPECULATIVE_BATTERY_TECH = "SPECULATIVE_BATTERY_TECH"
    HYDROGEN_FUEL_CELL_INFRA_KOREA = "HYDROGEN_FUEL_CELL_INFRA_KOREA"
    SOLAR_US_LOCALIZATION_SUPPLYCHAIN = "SOLAR_US_LOCALIZATION_SUPPLYCHAIN"
    WIND_POLICY_PERMITTING_RISK = "WIND_POLICY_PERMITTING_RISK"
    BATTERY_SAFETY_INDUSTRIAL_ACCIDENT_OVERLAY = "BATTERY_SAFETY_INDUSTRIAL_ACCIDENT_OVERLAY"
    EV_BATTERY_TRANSPARENCY_REGULATORY_OVERLAY = "EV_BATTERY_TRANSPARENCY_REGULATORY_OVERLAY"
    COMMODITY_SPREAD = "COMMODITY_SPREAD"
    REFINING_OIL_SPREAD = "REFINING_OIL_SPREAD"
    REFINING_SPREAD_TURNAROUND_KOREA = "REFINING_SPREAD_TURNAROUND_KOREA"
    REFINING_PETCHEM_MIX_DRAG = "REFINING_PETCHEM_MIX_DRAG"
    LUBRICANTS_HIGH_MARGIN_MIX = "LUBRICANTS_HIGH_MARGIN_MIX"
    CHEMICAL_SPREAD = "CHEMICAL_SPREAD"
    PETROCHEMICAL_RESTRUCTURING_KOREA = "PETROCHEMICAL_RESTRUCTURING_KOREA"
    NCC_CAPACITY_CUT_STAGE2 = "NCC_CAPACITY_CUT_STAGE2"
    NCC_OVERLOAD_SHAHEEN_RISK = "NCC_OVERLOAD_SHAHEEN_RISK"
    SPECIALTY_CHEM_GOVERNANCE_RESTRUCTURING = "SPECIALTY_CHEM_GOVERNANCE_RESTRUCTURING"
    SYNTHETIC_RUBBER_TARIFF_RISK = "SYNTHETIC_RUBBER_TARIFF_RISK"
    TIRE_RUBBER_PRODUCTION_DISRUPTION = "TIRE_RUBBER_PRODUCTION_DISRUPTION"
    COMMODITY_SPREAD_CYCLE_NOT_STRUCTURAL = "COMMODITY_SPREAD_CYCLE_NOT_STRUCTURAL"
    STEEL_METAL_SPREAD = "STEEL_METAL_SPREAD"
    NONFERROUS_STRATEGIC_METALS = "NONFERROUS_STRATEGIC_METALS"
    COPPER_AI_GRID_STRUCTURAL_DEMAND = "COPPER_AI_GRID_STRUCTURAL_DEMAND"
    LITHIUM_BATTERY_RAW_MATERIAL = "LITHIUM_BATTERY_RAW_MATERIAL"
    PRECIOUS_METALS_SAFE_HAVEN_MINERS = "PRECIOUS_METALS_SAFE_HAVEN_MINERS"
    PAPER_PACKAGING_CYCLE = "PAPER_PACKAGING_CYCLE"
    AGRI_COMMODITY_INPUTS = "AGRI_COMMODITY_INPUTS"
    LNG_ENERGY_TRADING_DISTRIBUTION = "LNG_ENERGY_TRADING_DISTRIBUTION"
    GENERAL_TRADING_RESOURCE_INFRA = "GENERAL_TRADING_RESOURCE_INFRA"
    ENERGY_UTILITY_LNG_GAS = "ENERGY_UTILITY_LNG_GAS"
    EVENT_PREMIUM_GOVERNANCE_OVERLAY = "EVENT_PREMIUM_GOVERNANCE_OVERLAY"
    COMMODITY_PRICE_4C_OVERLAY = "COMMODITY_PRICE_4C_OVERLAY"
    RARE_METALS_PRICE_FLOOR_OFFTAKE = "RARE_METALS_PRICE_FLOOR_OFFTAKE"
    COPPER_AI_GRID_KOREA = "COPPER_AI_GRID_KOREA"
    COPPER_PROCESSING_PLUS_DEFENSE = "COPPER_PROCESSING_PLUS_DEFENSE"
    DEFENSE_AMMO_EVENT_PREMIUM = "DEFENSE_AMMO_EVENT_PREMIUM"
    POLYSILICON_NON_CHINA_SUPPLY_OPTION = "POLYSILICON_NON_CHINA_SUPPLY_OPTION"
    POLYSILICON_REPORT_NOT_CONTRACT = "POLYSILICON_REPORT_NOT_CONTRACT"
    STEEL_TARIFF_EVENT_KOREA = "STEEL_TARIFF_EVENT_KOREA"
    STEEL_EXPORT_TARIFF_4C = "STEEL_EXPORT_TARIFF_4C"
    SPECIALTY_STEEL_US_LOCALIZATION_OPTION = "SPECIALTY_STEEL_US_LOCALIZATION_OPTION"
    LITHIUM_PRICE_EVENT_KOREA = "LITHIUM_PRICE_EVENT_KOREA"
    RARE_EARTH_THEME_KOREA = "RARE_EARTH_THEME_KOREA"
    CHEMICAL_SPREAD_KOREA = "CHEMICAL_SPREAD_KOREA"
    RARE_EARTH_MAGNET_SUPPLY_CHAIN = "RARE_EARTH_MAGNET_SUPPLY_CHAIN"
    RARE_METALS_EXPORT_CONTROL_EVENT = "RARE_METALS_EXPORT_CONTROL_EVENT"
    RARE_EARTH_CAPITAL_RAISE_DILUTION = "RARE_EARTH_CAPITAL_RAISE_DILUTION"
    COPPER_PROCESSING_INPUT_COST_OVERLAY = "COPPER_PROCESSING_INPUT_COST_OVERLAY"
    NICKEL_SULFUR_HPAL_INPUT_COST = "NICKEL_SULFUR_HPAL_INPUT_COST"
    FERTILIZER_INPUT_COST_SULFURIC_ACID = "FERTILIZER_INPUT_COST_SULFURIC_ACID"
    GOLD_MINER_JURISDICTION_RERATING = "GOLD_MINER_JURISDICTION_RERATING"
    IRON_ORE_CHINA_DEMAND_CYCLE = "IRON_ORE_CHINA_DEMAND_CYCLE"
    PACKAGING_CONSOLIDATION_REMEDY = "PACKAGING_CONSOLIDATION_REMEDY"
    SHIPPING_FREIGHT_CYCLE = "SHIPPING_FREIGHT_CYCLE"
    AUTO_MOBILITY_COMPONENTS = "AUTO_MOBILITY_COMPONENTS"
    AUTO_MOBILITY_COMPLETED_VEHICLE = "AUTO_MOBILITY_COMPLETED_VEHICLE"
    AUTO_HYBRID_LOCALIZATION_KOREA = "AUTO_HYBRID_LOCALIZATION_KOREA"
    AUTO_SDV_DELAY_CAPEX_OVERLAY = "AUTO_SDV_DELAY_CAPEX_OVERLAY"
    AUTO_PRICE_WAR_EUROPE_OVERLAY = "AUTO_PRICE_WAR_EUROPE_OVERLAY"
    AUTO_COMPONENT_RESTRUCTURING_KOREA = "AUTO_COMPONENT_RESTRUCTURING_KOREA"
    AUTO_COMPONENT_QUALITY_RECALL_OVERLAY = "AUTO_COMPONENT_QUALITY_RECALL_OVERLAY"
    AUTO_HYBRID_VALUEUP = "AUTO_HYBRID_VALUEUP"
    AUTO_TARIFF_LOCALIZATION = "AUTO_TARIFF_LOCALIZATION"
    AUTO_US_LOCALIZATION_LABOR_VISA_RISK = "AUTO_US_LOCALIZATION_LABOR_VISA_RISK"
    HYBRID_COMPONENT_BOTTLENECK = "HYBRID_COMPONENT_BOTTLENECK"
    TIRE_AUTO_COMPONENT_SPREAD = "TIRE_AUTO_COMPONENT_SPREAD"
    AIRLINE_TRAVEL_CYCLE = "AIRLINE_TRAVEL_CYCLE"
    CASINO_DUTYFREE_TOURISM = "CASINO_DUTYFREE_TOURISM"
    ECOMMERCE_LOGISTICS_REPEAT_CONTRACT = "ECOMMERCE_LOGISTICS_REPEAT_CONTRACT"
    LOGISTICS_LABOR_REGULATION_OVERLAY = "LOGISTICS_LABOR_REGULATION_OVERLAY"
    CASINO_DUTYFREE_TOURISM_POLICY_KOREA = "CASINO_DUTYFREE_TOURISM_POLICY_KOREA"
    CASINO_RETURN_VISITOR_UNIT_ECONOMICS = "CASINO_RETURN_VISITOR_UNIT_ECONOMICS"
    AIRLINE_SAFETY_REGULATORY_OVERLAY = "AIRLINE_SAFETY_REGULATORY_OVERLAY"
    SHIPPING_FREIGHT_CYCLE_KOREA = "SHIPPING_FREIGHT_CYCLE_KOREA"
    PARCEL_VOLUME_PRICE_COST_SPREAD = "PARCEL_VOLUME_PRICE_COST_SPREAD"
    TRAVEL_AGENCY_POLICY_EVENT = "TRAVEL_AGENCY_POLICY_EVENT"
    LOGISTICS_PARCEL_FREIGHT = "LOGISTICS_PARCEL_FREIGHT"
    RENTAL_USED_CAR_MOBILITY = "RENTAL_USED_CAR_MOBILITY"
    MOBILITY_RENTAL_MICROMOBILITY = "MOBILITY_RENTAL_MICROMOBILITY"
    AUTO_COMPONENTS_EV_ADAS = "AUTO_COMPONENTS_EV_ADAS"
    AUTONOMOUS_ROBOTAXI_DEPLOYMENT = "AUTONOMOUS_ROBOTAXI_DEPLOYMENT"
    ROBOTAXI_OPERATIONAL_REALITY_CHECK = "ROBOTAXI_OPERATIONAL_REALITY_CHECK"
    ROBOTAXI_SAFETY_REGULATORY_OVERLAY = "ROBOTAXI_SAFETY_REGULATORY_OVERLAY"
    AV_CRASH_DISCLOSURE_PROBE_OVERLAY = "AV_CRASH_DISCLOSURE_PROBE_OVERLAY"
    AUTONOMOUS_TRUCKING_COMMERCIAL_LAUNCH = "AUTONOMOUS_TRUCKING_COMMERCIAL_LAUNCH"
    AUTONOMOUS_TRUCKING_PAID_FREIGHT_MILESTONE = "AUTONOMOUS_TRUCKING_PAID_FREIGHT_MILESTONE"
    AUTONOMOUS_TRUCKING_UNIT_ECONOMICS = "AUTONOMOUS_TRUCKING_UNIT_ECONOMICS"
    TOURISM_POLICY_EVENT = "TOURISM_POLICY_EVENT"
    URBAN_AIR_DRONE = "URBAN_AIR_DRONE"
    EVTOL_CERTIFICATION_CASH_BURN = "EVTOL_CERTIFICATION_CASH_BURN"
    PART135_NOT_TYPE_CERTIFICATION = "PART135_NOT_TYPE_CERTIFICATION"
    SPACE_SUPPLYCHAIN = "SPACE_SUPPLYCHAIN"
    SATELLITE_CONNECTIVITY_INFRA = "SATELLITE_CONNECTIVITY_INFRA"
    AIRLINE_INTEGRATION_SCALE = "AIRLINE_INTEGRATION_SCALE"
    TRANSPORT_SAFETY_REGULATORY_OVERLAY = "TRANSPORT_SAFETY_REGULATORY_OVERLAY"
    FLEET_UNIT_ECONOMICS_OVERLAY = "FLEET_UNIT_ECONOMICS_OVERLAY"
    EV_RENTAL_UNIT_ECONOMICS = "EV_RENTAL_UNIT_ECONOMICS"
    ROBOTICS_FACTORY_AUTOMATION = "ROBOTICS_FACTORY_AUTOMATION"
    AI_DATA_CENTER_INFRASTRUCTURE = "AI_DATA_CENTER_INFRASTRUCTURE"
    NUCLEAR_SMR_GRID_POLICY = "NUCLEAR_SMR_GRID_POLICY"
    TRAVEL_LEISURE_REOPENING = "TRAVEL_LEISURE_REOPENING"
    EDUCATION_SPECIALTY_SERVICES = "EDUCATION_SPECIALTY_SERVICES"
    RARE_METALS_STRATEGIC_MATERIALS = "RARE_METALS_STRATEGIC_MATERIALS"
    VALUE_UP_SHAREHOLDER_RETURN = "VALUE_UP_SHAREHOLDER_RETURN"
    PLATFORM_SOFTWARE_INTERNET = "PLATFORM_SOFTWARE_INTERNET"
    B2B_SAAS_ERP_WORKFLOW = "B2B_SAAS_ERP_WORKFLOW"
    B2B_SAAS_ERP_WORKFLOW_KOREA = "B2B_SAAS_ERP_WORKFLOW_KOREA"
    ENTERPRISE_AI_CLOUD_INFRA_KOREA = "ENTERPRISE_AI_CLOUD_INFRA_KOREA"
    PRIVATE_EQUITY_SOFTWARE_RERATING = "PRIVATE_EQUITY_SOFTWARE_RERATING"
    AI_CLOUD_CAPITAL_ALLOCATION = "AI_CLOUD_CAPITAL_ALLOCATION"
    SOVEREIGN_KOREAN_AI_MODEL = "SOVEREIGN_KOREAN_AI_MODEL"
    WEBTOON_PLATFORM_IP_MONETIZATION = "WEBTOON_PLATFORM_IP_MONETIZATION"
    ENTERPRISE_AI_ONTOLOGY_WORKFLOW = "ENTERPRISE_AI_ONTOLOGY_WORKFLOW"
    GOVERNMENT_AI_PROGRAM_OF_RECORD = "GOVERNMENT_AI_PROGRAM_OF_RECORD"
    CLOUD_AI_SOFTWARE_INFRA = "CLOUD_AI_SOFTWARE_INFRA"
    EDGE_AI_CLOUD_INFRASTRUCTURE = "EDGE_AI_CLOUD_INFRASTRUCTURE"
    AI_SOFTWARE_APPLICATION = "AI_SOFTWARE_APPLICATION"
    LEGACY_SAAS_AI_REINFORCEMENT = "LEGACY_SAAS_AI_REINFORCEMENT"
    LEGACY_SAAS_AI_DISRUPTION_OVERLAY = "LEGACY_SAAS_AI_DISRUPTION_OVERLAY"
    OBSERVABILITY_AI_OPERATIONS = "OBSERVABILITY_AI_OPERATIONS"
    OBSERVABILITY_GUIDANCE_RISK = "OBSERVABILITY_GUIDANCE_RISK"
    GENERATIVE_AI_IP_RISK = "GENERATIVE_AI_IP_RISK"
    CONTACT_CENTER_AI_AUTOMATION = "CONTACT_CENTER_AI_AUTOMATION"
    SERVICE_KIOSK_SELF_CHECKOUT = "SERVICE_KIOSK_SELF_CHECKOUT"
    GAME_CONTENT_IP = "GAME_CONTENT_IP"
    GAME_CONTENT_IP_REPEAT_MONETIZATION = "GAME_CONTENT_IP_REPEAT_MONETIZATION"
    GAME_SINGLE_IP_EVENT_PREMIUM = "GAME_SINGLE_IP_EVENT_PREMIUM"
    GAME_IP_LAUNCH_DELAY_LEGAL_RISK = "GAME_IP_LAUNCH_DELAY_LEGAL_RISK"
    SINGLE_IP_RELEASE_EVENT_PREMIUM = "SINGLE_IP_RELEASE_EVENT_PREMIUM"
    UGC_GAME_PLATFORM_SAFETY = "UGC_GAME_PLATFORM_SAFETY"
    KPOP_PLATFORM_CONTENT_IP = "KPOP_PLATFORM_CONTENT_IP"
    ENTERTAINMENT_GOVERNANCE_LEGAL_OVERLAY = "ENTERTAINMENT_GOVERNANCE_LEGAL_OVERLAY"
    AD_CONTENT_PLATFORM_GUIDANCE_RISK = "AD_CONTENT_PLATFORM_GUIDANCE_RISK"
    MEDIA_AD_CONTENT_CYCLE = "MEDIA_AD_CONTENT_CYCLE"
    ADTECH_PLATFORM_PREMIUM = "ADTECH_PLATFORM_PREMIUM"
    STREAMING_AD_PLATFORM = "STREAMING_AD_PLATFORM"
    CYBERSECURITY_AI_THREAT_DEMAND = "CYBERSECURITY_AI_THREAT_DEMAND"
    AI_NETWORKING_SOFTWARE_INFRA_CROSSOVER = "AI_NETWORKING_SOFTWARE_INFRA_CROSSOVER"
    SECURITY_IDENTITY_DEEPFAKE = "SECURITY_IDENTITY_DEEPFAKE"
    SECURITY_OPERATIONAL_TRUST_OVERLAY = "SECURITY_OPERATIONAL_TRUST_OVERLAY"
    METAVERSE_NFT_THEME = "METAVERSE_NFT_THEME"
    PLATFORM_GOVERNANCE_LEGAL_RISK = "PLATFORM_GOVERNANCE_LEGAL_RISK"
    PLATFORM_AD_TRUST_OVERLAY = "PLATFORM_AD_TRUST_OVERLAY"
    PLATFORM_PRIVACY_SECURITY_OVERLAY = "PLATFORM_PRIVACY_SECURITY_OVERLAY"
    PLATFORM_PRIVACY_YOUTH_SAFETY_OVERLAY = "PLATFORM_PRIVACY_YOUTH_SAFETY_OVERLAY"
    FINANCIAL_SPREAD_BALANCE_SHEET = "FINANCIAL_SPREAD_BALANCE_SHEET"
    BANK_HOLDING_VALUEUP_CAPITAL_RETURN = "BANK_HOLDING_VALUEUP_CAPITAL_RETURN"
    BANK_HOLDING_VALUEUP_CAPITAL_RETURN_KOREA = "BANK_HOLDING_VALUEUP_CAPITAL_RETURN_KOREA"
    BANK_ROE_PBR_RERATING_KOREA = "BANK_ROE_PBR_RERATING_KOREA"
    BANK_CREDIT_COST_PF_OVERLAY = "BANK_CREDIT_COST_PF_OVERLAY"
    REGIONAL_BANK_HIGH_ROE_VALUEUP = "REGIONAL_BANK_HIGH_ROE_VALUEUP"
    INSURANCE_UNDERWRITING_CYCLE = "INSURANCE_UNDERWRITING_CYCLE"
    INSURANCE_CAPITAL_RELEASE_VALUEUP = "INSURANCE_CAPITAL_RELEASE_VALUEUP"
    INSURANCE_CAPITAL_RELEASE_VALUEUP_KOREA = "INSURANCE_CAPITAL_RELEASE_VALUEUP_KOREA"
    INSURANCE_KICS_CSM_GATE = "INSURANCE_KICS_CSM_GATE"
    INSURANCE_NAV_VALUEUP_SAMSUNG_ELECTRONICS_STAKE = "INSURANCE_NAV_VALUEUP_SAMSUNG_ELECTRONICS_STAKE"
    SECURITIES_BROKERAGE_CYCLE = "SECURITIES_BROKERAGE_CYCLE"
    SECURITIES_BROKERAGE_MARKET_BETA = "SECURITIES_BROKERAGE_MARKET_BETA"
    SECURITIES_IB_PF_RISK_OVERLAY = "SECURITIES_IB_PF_RISK_OVERLAY"
    INTERNET_BANK_PROFITABILITY = "INTERNET_BANK_PROFITABILITY"
    TREASURY_SHARE_CANCEL_EXECUTION = "TREASURY_SHARE_CANCEL_EXECUTION"
    TREASURY_CANCEL_MANDATE_POLICY = "TREASURY_CANCEL_MANDATE_POLICY"
    BUYBACK_CANCEL_BUT_BUSINESS_RISK = "BUYBACK_CANCEL_BUT_BUSINESS_RISK"
    BUYBACK_EXECUTION_PRICE_FAILED = "BUYBACK_EXECUTION_PRICE_FAILED"
    SHAREHOLDER_RETURN_COMPOUNDING_FINANCIAL_HOLDCO = "SHAREHOLDER_RETURN_COMPOUNDING_FINANCIAL_HOLDCO"
    PAYMENT_FINTECH_INFRA = "PAYMENT_FINTECH_INFRA"
    PAYMENT_BIOMETRIC_INFRASTRUCTURE = "PAYMENT_BIOMETRIC_INFRASTRUCTURE"
    PAYMENT_PRIVACY_REGULATORY_4C = "PAYMENT_PRIVACY_REGULATORY_4C"
    FINTECH_SUPERAPP_IPO_OPTION = "FINTECH_SUPERAPP_IPO_OPTION"
    FINTECH_SUPERAPP_IPO_OPTION_KOREA = "FINTECH_SUPERAPP_IPO_OPTION_KOREA"
    FINTECH_IPO_VALUATION_RISK = "FINTECH_IPO_VALUATION_RISK"
    KRW_STABLECOIN_INFRA_OPTION = "KRW_STABLECOIN_INFRA_OPTION"
    KRW_STABLECOIN_POLICY_OPTION = "KRW_STABLECOIN_POLICY_OPTION"
    KRW_STABLECOIN_POLICY_THEME = "KRW_STABLECOIN_POLICY_THEME"
    DIGITAL_ASSET_TOKENIZATION = "DIGITAL_ASSET_TOKENIZATION"
    DIGITAL_ASSET_BANK_EQUITY_OPTION = "DIGITAL_ASSET_BANK_EQUITY_OPTION"
    CREDIT_DATA_INFRA = "CREDIT_DATA_INFRA"
    CREDIT_INFORMATION_RECURRING_DATA = "CREDIT_INFORMATION_RECURRING_DATA"
    VC_EXIT_MARKET_CYCLE = "VC_EXIT_MARKET_CYCLE"
    EVENT_PREMIUM_GOVERNANCE_BATTLE = "EVENT_PREMIUM_GOVERNANCE_BATTLE"
    REGULATED_STABLECOIN_INFRA = "REGULATED_STABLECOIN_INFRA"
    STABLECOIN_AI_AGENT_PAYMENT_OPTION = "STABLECOIN_AI_AGENT_PAYMENT_OPTION"
    STABLECOIN_REGULATORY_ECONOMICS = "STABLECOIN_REGULATORY_ECONOMICS"
    ALGORITHMIC_STABLECOIN_FAILURE = "ALGORITHMIC_STABLECOIN_FAILURE"
    DIGITAL_ASSET_EXCHANGE_CONSOLIDATION = "DIGITAL_ASSET_EXCHANGE_CONSOLIDATION"
    DIGITAL_ASSET_EXCHANGE_EQUITY_OPTION = "DIGITAL_ASSET_EXCHANGE_EQUITY_OPTION"
    BANK_DIGITAL_ASSET_EQUITY_STAKE = "BANK_DIGITAL_ASSET_EQUITY_STAKE"
    EXCHANGE_SECURITY_OPERATIONAL_RISK = "EXCHANGE_SECURITY_OPERATIONAL_RISK"
    GUARANTEE_INSURANCE_IPO_SECURITY_RISK = "GUARANTEE_INSURANCE_IPO_SECURITY_RISK"
    DIGITAL_ASSET_THEME_OVERHEAT = "DIGITAL_ASSET_THEME_OVERHEAT"
    VALUE_UP_CROWDED_4B_WATCH = "VALUE_UP_CROWDED_4B_WATCH"
    GOVERNANCE_EXECUTION_FAILURE_OVERLAY = "GOVERNANCE_EXECUTION_FAILURE_OVERLAY"
    TAX_POLICY_MARKET_SHOCK_OVERLAY = "TAX_POLICY_MARKET_SHOCK_OVERLAY"
    POLICY_TAX_REVERSAL_MARKET_SHOCK = "POLICY_TAX_REVERSAL_MARKET_SHOCK"
    AI_WINDFALL_CITIZEN_DIVIDEND_POLICY_SHOCK = "AI_WINDFALL_CITIZEN_DIVIDEND_POLICY_SHOCK"
    STABLECOIN_BANK_DEPOSIT_DISINTERMEDIATION = "STABLECOIN_BANK_DEPOSIT_DISINTERMEDIATION"
    STABLECOIN_CONVERTIBILITY_OVERLAY = "STABLECOIN_CONVERTIBILITY_OVERLAY"
    BIOTECH_REGULATORY = "BIOTECH_REGULATORY"
    BIOTECH_PRE_REVENUE_REGULATORY = "BIOTECH_PRE_REVENUE_REGULATORY"
    BIOTECH_ROYALTY_COMMERCIALIZATION = "BIOTECH_ROYALTY_COMMERCIALIZATION"
    CDMO_HEALTHCARE_CONTRACT = "CDMO_HEALTHCARE_CONTRACT"
    CDMO_US_TARIFF_HEDGE_CAPACITY = "CDMO_US_TARIFF_HEDGE_CAPACITY"
    CDMO_ADC_CELL_GENE_CAPABILITY = "CDMO_ADC_CELL_GENE_CAPABILITY"
    CRO_CLINICAL_SERVICE = "CRO_CLINICAL_SERVICE"
    CRO_FUNDING_CYCLE_OVERLAY = "CRO_FUNDING_CYCLE_OVERLAY"
    BIOSIMILAR_COMMERCIALIZATION = "BIOSIMILAR_COMMERCIALIZATION"
    BIOSIMILAR_ACCESS_CASH_PAY = "BIOSIMILAR_ACCESS_CASH_PAY"
    BIOSIMILAR_PBM_FORMULARY_SWITCH = "BIOSIMILAR_PBM_FORMULARY_SWITCH"
    BIOSIMILAR_ORIGINATOR_DEFENSE = "BIOSIMILAR_ORIGINATOR_DEFENSE"
    BIOSIMILAR_PATENT_LITIGATION = "BIOSIMILAR_PATENT_LITIGATION"
    OBESITY_GLP1_COMMERCIALIZATION = "OBESITY_GLP1_COMMERCIALIZATION"
    ORAL_GLP1_APPROVAL_COMMERCIALIZATION = "ORAL_GLP1_APPROVAL_COMMERCIALIZATION"
    ORAL_GLP1_MAINTENANCE_THERAPY = "ORAL_GLP1_MAINTENANCE_THERAPY"
    GLP1_PRICE_WAR_OVERLAY = "GLP1_PRICE_WAR_OVERLAY"
    GLP1_TELEHEALTH_CHANNEL = "GLP1_TELEHEALTH_CHANNEL"
    COMPOUNDED_GLP1_REGULATORY_RISK = "COMPOUNDED_GLP1_REGULATORY_RISK"
    GENE_THERAPY_RARE_DISEASE = "GENE_THERAPY_RARE_DISEASE"
    AI_DRUG_DISCOVERY_PLATFORM = "AI_DRUG_DISCOVERY_PLATFORM"
    DIGITAL_HEALTHCARE_AI = "DIGITAL_HEALTHCARE_AI"
    MEDICAL_AI_EXTERNAL_VALIDATION = "MEDICAL_AI_EXTERNAL_VALIDATION"
    MEDICAL_AI_SUBGROUP_GENERALIZATION_RISK = "MEDICAL_AI_SUBGROUP_GENERALIZATION_RISK"
    DIGITAL_HEALTHCARE_REMOTE_MEDICINE = "DIGITAL_HEALTHCARE_REMOTE_MEDICINE"
    TELEHEALTH_BEHAVIORAL_HEALTH = "TELEHEALTH_BEHAVIORAL_HEALTH"
    PHARMA_CHANNEL_AND_PRIVACY_RISK = "PHARMA_CHANNEL_AND_PRIVACY_RISK"
    MEDICAL_DEVICE_HEALTHCARE_EXPORT = "MEDICAL_DEVICE_HEALTHCARE_EXPORT"
    MEDICAL_DEVICE_DENTAL_IMPLANT = "MEDICAL_DEVICE_DENTAL_IMPLANT"
    SURGICAL_ROBOT_INSTALLED_BASE = "SURGICAL_ROBOT_INSTALLED_BASE"
    SURGICAL_ROBOT_GLP1_PROCEDURE_MIX_OVERLAY = "SURGICAL_ROBOT_GLP1_PROCEDURE_MIX_OVERLAY"
    BOTULINUM_AESTHETIC_REGULATED = "BOTULINUM_AESTHETIC_REGULATED"
    DIAGNOSTICS_INFECTIOUS_DISEASE = "DIAGNOSTICS_INFECTIOUS_DISEASE"
    COMMERCIALIZATION_FAILURE_OVERLAY = "COMMERCIALIZATION_FAILURE_OVERLAY"
    REIMBURSEMENT_ACCESS_OVERLAY = "REIMBURSEMENT_ACCESS_OVERLAY"
    DEVICE_SAFETY_COUNTERFEIT_OVERLAY = "DEVICE_SAFETY_COUNTERFEIT_OVERLAY"
    SC_FORMULATION_ROYALTY_PLATFORM = "SC_FORMULATION_ROYALTY_PLATFORM"
    BLOCKBUSTER_LIFE_EXTENSION_ROYALTY = "BLOCKBUSTER_LIFE_EXTENSION_ROYALTY"
    KOREA_ONCOLOGY_DRUG_COMMERCIALIZATION = "KOREA_ONCOLOGY_DRUG_COMMERCIALIZATION"
    BIOSIMILAR_TARIFF_HEDGE_MANUFACTURING = "BIOSIMILAR_TARIFF_HEDGE_MANUFACTURING"
    BIOSIMILAR_COMMERCIALIZATION_KOREA = "BIOSIMILAR_COMMERCIALIZATION_KOREA"
    BOTULINUM_US_MARKET_ENTRY = "BOTULINUM_US_MARKET_ENTRY"
    AESTHETIC_DEVICE_EXPORT_KOREA = "AESTHETIC_DEVICE_EXPORT_KOREA"
    BIOTECH_LICENSE_MILESTONE_PLATFORM = "BIOTECH_LICENSE_MILESTONE_PLATFORM"
    GLP1_GENERIC_THEME_KOREA = "GLP1_GENERIC_THEME_KOREA"
    MEDICAL_AI_REIMBURSEMENT_KOREA = "MEDICAL_AI_REIMBURSEMENT_KOREA"
    APPROVAL_ONLY_NOT_COMMERCIALIZATION = "APPROVAL_ONLY_NOT_COMMERCIALIZATION"
    MANUFACTURING_INSPECTION_CRL_OVERLAY = "MANUFACTURING_INSPECTION_CRL_OVERLAY"
    PATENT_CHALLENGE_OVERLAY = "PATENT_CHALLENGE_OVERLAY"
    DEVICE_SAFETY_CHANNEL_OVERLAY = "DEVICE_SAFETY_CHANNEL_OVERLAY"
    ANIMAL_HEALTH_BIOSECURITY = "ANIMAL_HEALTH_BIOSECURITY"
    RETAIL_DOMESTIC_CONSUMER = "RETAIL_DOMESTIC_CONSUMER"
    FOOD_AGRI_LIVESTOCK_CYCLE = "FOOD_AGRI_LIVESTOCK_CYCLE"
    RETAIL_CONVENIENCE_OFFLINE = "RETAIL_CONVENIENCE_OFFLINE"
    RETAIL_ECOMMERCE_LOGISTICS = "RETAIL_ECOMMERCE_LOGISTICS"
    ECOMMERCE_FRESH_LOGISTICS = "ECOMMERCE_FRESH_LOGISTICS"
    BEAUTY_OEM_ODM_SUPPLYCHAIN = "BEAUTY_OEM_ODM_SUPPLYCHAIN"
    APPAREL_FAST_FASHION_BRAND_OEM = "APPAREL_FAST_FASHION_BRAND_OEM"
    HOME_LIVING_APPLIANCE_RENTAL = "HOME_LIVING_APPLIANCE_RENTAL"
    K_FOOD_GLOBAL_PORTFOLIO_EXPANSION = "K_FOOD_GLOBAL_PORTFOLIO_EXPANSION"
    K_FOOD_GLOBAL_LOCALIZATION = "K_FOOD_GLOBAL_LOCALIZATION"
    K_FOOD_VIRAL_BRAND_CULTURE = "K_FOOD_VIRAL_BRAND_CULTURE"
    K_FOOD_GLOBAL_STAPLE_BRAND = "K_FOOD_GLOBAL_STAPLE_BRAND"
    K_FOOD_GLOBAL_STAPLE_BRAND_SECOND_WAVE = "K_FOOD_GLOBAL_STAPLE_BRAND_SECOND_WAVE"
    K_FOOD_SINGLE_SKU_RISK = "K_FOOD_SINGLE_SKU_RISK"
    K_FOOD_SINGLE_SKU_EXPORT_RISK = "K_FOOD_SINGLE_SKU_EXPORT_RISK"
    K_BEAUTY_OFFLINE_SELL_THROUGH = "K_BEAUTY_OFFLINE_SELL_THROUGH"
    K_BEAUTY_RETAIL_PLATFORM = "K_BEAUTY_RETAIL_PLATFORM"
    K_BEAUTY_RETAIL_PLATFORM_OPTION = "K_BEAUTY_RETAIL_PLATFORM_OPTION"
    K_BEAUTY_EXPORT_DISTRIBUTION_KOREA = "K_BEAUTY_EXPORT_DISTRIBUTION_KOREA"
    K_BEAUTY_BRAND_US_CHANNEL = "K_BEAUTY_BRAND_US_CHANNEL"
    K_BEAUTY_BRAND_SECOND_WAVE = "K_BEAUTY_BRAND_SECOND_WAVE"
    K_BEAUTY_OEM_ODM_SUPPLYCHAIN_KOREA = "K_BEAUTY_OEM_ODM_SUPPLYCHAIN_KOREA"
    K_BEAUTY_BRAND_MNA_VALIDATION_STAGE2_REFERENCE = "K_BEAUTY_BRAND_MNA_VALIDATION_STAGE2_REFERENCE"
    K_BEAUTY_TARIFF_IMPORT_REVIEW = "K_BEAUTY_TARIFF_IMPORT_REVIEW"
    ECOMMERCE_RESTRUCTURING_JV_KOREA = "ECOMMERCE_RESTRUCTURING_JV_KOREA"
    RETAIL_PLATFORM_DATA_REGULATION_OVERLAY = "RETAIL_PLATFORM_DATA_REGULATION_OVERLAY"
    DEPARTMENT_STORE_MALL_REDEVELOPMENT = "DEPARTMENT_STORE_MALL_REDEVELOPMENT"
    CONVENIENCE_STORE_PB_SSSG_KOREA = "CONVENIENCE_STORE_PB_SSSG_KOREA"
    TARIFF_IMPORT_MARGIN_OVERLAY = "TARIFF_IMPORT_MARGIN_OVERLAY"
    BEAUTY_DEVICE_AFFILIATE_COMMERCE = "BEAUTY_DEVICE_AFFILIATE_COMMERCE"
    BEAUTY_DEVICE_REGULATORY_SAFETY = "BEAUTY_DEVICE_REGULATORY_SAFETY"
    BEAUTY_FAST_PRODUCT_CYCLE_RISK = "BEAUTY_FAST_PRODUCT_CYCLE_RISK"
    APPAREL_LICENSE_BRAND_CHINA_RISK = "APPAREL_LICENSE_BRAND_CHINA_RISK"
    CHINA_CONSUMER_EXPOSURE_4C = "CHINA_CONSUMER_EXPOSURE_4C"
    STRONG_PRIVATE_PLATFORM_BUT_HOLDCO_LINK_CAP = "STRONG_PRIVATE_PLATFORM_BUT_HOLDCO_LINK_CAP"
    ULTRA_LOW_COST_CROSSBORDER_PLATFORM = "ULTRA_LOW_COST_CROSSBORDER_PLATFORM"
    ECOMMERCE_TRUST_SECURITY = "ECOMMERCE_TRUST_SECURITY"
    ECOMMERCE_SUPPLIER_MARGIN_QUALITY = "ECOMMERCE_SUPPLIER_MARGIN_QUALITY"
    FAST_FASHION_IP_SUPPLIER_LITIGATION = "FAST_FASHION_IP_SUPPLIER_LITIGATION"
    FAST_FASHION_PRODUCT_SAFETY_DSA = "FAST_FASHION_PRODUCT_SAFETY_DSA"
    HOME_APPLIANCE_HARDWARE_CYCLE = "HOME_APPLIANCE_HARDWARE_CYCLE"
    DISCOUNT_PROMOTION_MARGIN_OVERLAY = "DISCOUNT_PROMOTION_MARGIN_OVERLAY"
    HOME_CHILD_EDUCATION = "HOME_CHILD_EDUCATION"
    CONSUMER_REGULATED_PRODUCT = "CONSUMER_REGULATED_PRODUCT"
    BEAUTY_DEVICE_EXPORT = "BEAUTY_DEVICE_EXPORT"
    FOOD_SAFETY_RECALL_OVERLAY = "FOOD_SAFETY_RECALL_OVERLAY"
    DATA_SECURITY_SUPPLIER_REGULATION_OVERLAY = "DATA_SECURITY_SUPPLIER_REGULATION_OVERLAY"
    SMART_FARM_AGRI_TECH = "SMART_FARM_AGRI_TECH"
    VERTICAL_FARMING_UNIT_ECONOMICS = "VERTICAL_FARMING_UNIT_ECONOMICS"
    AGRI_MACHINERY_PRECISION_CYCLE = "AGRI_MACHINERY_PRECISION_CYCLE"
    AGRI_MACHINERY_DEMAND_CYCLE = "AGRI_MACHINERY_DEMAND_CYCLE"
    AGRI_MACHINERY_SOFTWARE_LOCKIN = "AGRI_MACHINERY_SOFTWARE_LOCKIN"
    RIGHT_TO_REPAIR_REGULATORY_OVERLAY = "RIGHT_TO_REPAIR_REGULATORY_OVERLAY"
    RIGHT_TO_REPAIR_CONSTRUCTION_EXPANSION = "RIGHT_TO_REPAIR_CONSTRUCTION_EXPANSION"
    AGRI_INPUT_SEED_CROP_PROTECTION = "AGRI_INPUT_SEED_CROP_PROTECTION"
    FERTILIZER_INPUT_COST_CYCLE = "FERTILIZER_INPUT_COST_CYCLE"
    FERTILIZER_STRATEGIC_PHOSPHATE_OPTION = "FERTILIZER_STRATEGIC_PHOSPHATE_OPTION"
    AGRI_LIVESTOCK_FOOD_COMMODITY = "AGRI_LIVESTOCK_FOOD_COMMODITY"
    LIVESTOCK_DISEASE_PRICE_REGULATORY = "LIVESTOCK_DISEASE_PRICE_REGULATORY"
    AGRI_DISEASE_AI_MONITORING = "AGRI_DISEASE_AI_MONITORING"
    FOOD_INPUT_REGULATED_CYCLE = "FOOD_INPUT_REGULATED_CYCLE"
    EDTECH_AI_MONETIZATION_TRADEOFF = "EDTECH_AI_MONETIZATION_TRADEOFF"
    EDTECH_AI_DISRUPTION = "EDTECH_AI_DISRUPTION"
    EDTECH_AI_SEARCH_DISINTERMEDIATION = "EDTECH_AI_SEARCH_DISINTERMEDIATION"
    ONLINE_EDUCATION_OPM_DISTRESS = "ONLINE_EDUCATION_OPM_DISTRESS"
    NICOTINE_ALTERNATIVE_REGULATED = "NICOTINE_ALTERNATIVE_REGULATED"
    SELF_CHECKOUT_LOCAL_REGULATION_OVERLAY = "SELF_CHECKOUT_LOCAL_REGULATION_OVERLAY"
    NICOTINE_POUCH_YOUTH_SAFETY_OVERLAY = "NICOTINE_POUCH_YOUTH_SAFETY_OVERLAY"
    CANNABIS_REGULATED_PRODUCT = "CANNABIS_REGULATED_PRODUCT"
    CANNABIS_PARTIAL_RESCHEDULING_LIMIT = "CANNABIS_PARTIAL_RESCHEDULING_LIMIT"
    POLICY_LOCAL_SERVICE_THEME = "POLICY_LOCAL_SERVICE_THEME"
    AGRI_DISEASE_EVENT_OVERLAY = "AGRI_DISEASE_EVENT_OVERLAY"
    AI_EDUCATION_DISRUPTION_OVERLAY = "AI_EDUCATION_DISRUPTION_OVERLAY"
    REGULATED_CONSUMER_APPROVAL_OVERLAY = "REGULATED_CONSUMER_APPROVAL_OVERLAY"
    CONSTRUCTION_REAL_ESTATE_CREDIT = "CONSTRUCTION_REAL_ESTATE_CREDIT"
    CONSTRUCTION_REAL_ESTATE_CREDIT_KOREA = "CONSTRUCTION_REAL_ESTATE_CREDIT_KOREA"
    PF_RESTRUCTURING_RELIEF = "PF_RESTRUCTURING_RELIEF"
    PF_RESTRUCTURING_RELIEF_KOREA = "PF_RESTRUCTURING_RELIEF_KOREA"
    PF_SYNDICATED_LOAN_SOFT_LANDING = "PF_SYNDICATED_LOAN_SOFT_LANDING"
    OVERSEAS_EPC_CONTRACT_BACKLOG_KOREA = "OVERSEAS_EPC_CONTRACT_BACKLOG_KOREA"
    EPC_LOW_MARGIN_ORDER_OVERLAY = "EPC_LOW_MARGIN_ORDER_OVERLAY"
    APARTMENT_QUALITY_SAFETY_OVERLAY = "APARTMENT_QUALITY_SAFETY_OVERLAY"
    LARGE_BUILDER_BALANCE_SHEET_DEFENSE = "LARGE_BUILDER_BALANCE_SHEET_DEFENSE"
    REIT_DEVELOPMENT_TRUST = "REIT_DEVELOPMENT_TRUST"
    K_REIT_DIVIDEND_COVERAGE = "K_REIT_DIVIDEND_COVERAGE"
    LOGISTICS_REIT_OCCUPANCY_KOREA = "LOGISTICS_REIT_OCCUPANCY_KOREA"
    BUILDING_MATERIALS_CYCLE = "BUILDING_MATERIALS_CYCLE"
    BUILDING_MATERIALS_PRICE_COST = "BUILDING_MATERIALS_PRICE_COST"
    BUILDING_MATERIALS_PRICE_COST_KOREA = "BUILDING_MATERIALS_PRICE_COST_KOREA"
    BUILDING_MATERIALS_VOLUME_FAILURE = "BUILDING_MATERIALS_VOLUME_FAILURE"
    CEMENT_REGULATORY_COLLUSION_OVERLAY = "CEMENT_REGULATORY_COLLUSION_OVERLAY"
    HOME_INTERIOR_HOUSING_CYCLE = "HOME_INTERIOR_HOUSING_CYCLE"
    LOW_CARBON_CEMENT_PREMIUM = "LOW_CARBON_CEMENT_PREMIUM"
    BUILDING_PRODUCTS_MNA_SHIFT = "BUILDING_PRODUCTS_MNA_SHIFT"
    PRECAST_WALLING_BUILDING_SOLUTIONS = "PRECAST_WALLING_BUILDING_SOLUTIONS"
    DATA_CENTER_REIT_INFRASTRUCTURE = "DATA_CENTER_REIT_INFRASTRUCTURE"
    DATA_CENTER_REIT_IPO_NO_ASSET = "DATA_CENTER_REIT_IPO_NO_ASSET"
    DATA_CENTER_SPONSOR_PREMIUM_PIPELINE = "DATA_CENTER_SPONSOR_PREMIUM_PIPELINE"
    DATA_CENTER_POWER_WATER_PERMITTING = "DATA_CENTER_POWER_WATER_PERMITTING"
    DATA_CENTER_LOCAL_MORATORIUM_OVERLAY = "DATA_CENTER_LOCAL_MORATORIUM_OVERLAY"
    DATA_CENTER_LOCAL_OPPOSITION_OVERLAY = "DATA_CENTER_LOCAL_OPPOSITION_OVERLAY"
    DATA_CENTER_WATER_RIGHTS_REFERENDUM = "DATA_CENTER_WATER_RIGHTS_REFERENDUM"
    DATA_CENTER_RATEPAYER_UTILITY_COST_OVERLAY = "DATA_CENTER_RATEPAYER_UTILITY_COST_OVERLAY"
    DATA_CENTER_CAPEX_AFFO_DILUTION = "DATA_CENTER_CAPEX_AFFO_DILUTION"
    AI_POWER_DATA_CENTER_CAMPUS = "AI_POWER_DATA_CENTER_CAMPUS"
    AI_DATA_CENTER_POWER_CAMPUS = "AI_DATA_CENTER_POWER_CAMPUS"
    AI_DATA_CENTER_REAL_ASSET_KOREA = "AI_DATA_CENTER_REAL_ASSET_KOREA"
    AI_DATA_CENTER_NO_REVENUE_NO_TENANT = "AI_DATA_CENTER_NO_REVENUE_NO_TENANT"
    COLD_CHAIN_REIT_LOGISTICS = "COLD_CHAIN_REIT_LOGISTICS"
    COLD_CHAIN_DEBT_OCCUPANCY_RISK = "COLD_CHAIN_DEBT_OCCUPANCY_RISK"
    INFRA_RECONSTRUCTION_POLICY = "INFRA_RECONSTRUCTION_POLICY"
    POLICY_LOCAL_REAL_ESTATE_THEME = "POLICY_LOCAL_REAL_ESTATE_THEME"
    PF_CREDIT_REDTEAM_OVERLAY = "PF_CREDIT_REDTEAM_OVERLAY"
    REIT_AFFO_INTEGRITY_OVERLAY = "REIT_AFFO_INTEGRITY_OVERLAY"
    AI_INFRA_REAL_ASSET_THEME_OVERLAY = "AI_INFRA_REAL_ASSET_THEME_OVERLAY"
    DISASTER_REBUILD_EVENT = "DISASTER_REBUILD_EVENT"
    NORTH_KOREA_POLICY_EVENT = "NORTH_KOREA_POLICY_EVENT"
    GEOPOLITICAL_RECONSTRUCTION = "GEOPOLITICAL_RECONSTRUCTION"
    REAL_RECONSTRUCTION_FINANCING = "REAL_RECONSTRUCTION_FINANCING"
    CRITICAL_INFRA_RECONSTRUCTION_FINANCING = "CRITICAL_INFRA_RECONSTRUCTION_FINANCING"
    DOMESTIC_RESOURCE_DISCOVERY_EVENT = "DOMESTIC_RESOURCE_DISCOVERY_EVENT"
    RESOURCE_EXPLORATION_DRILL_BIT_GATE = "RESOURCE_EXPLORATION_DRILL_BIT_GATE"
    ENERGY_SECURITY_POLICY_EVENT = "ENERGY_SECURITY_POLICY_EVENT"
    MARKET_STRUCTURE_SHORT_SELLING_POLICY = "MARKET_STRUCTURE_SHORT_SELLING_POLICY"
    SHORT_SELLING_RESUMPTION_RISK = "SHORT_SELLING_RESUMPTION_RISK"
    POLITICAL_SYSTEM_SHOCK_KOREA = "POLITICAL_SYSTEM_SHOCK_KOREA"
    GEOPOLITICAL_ENERGY_IMPORT_SHOCK = "GEOPOLITICAL_ENERGY_IMPORT_SHOCK"
    EVENT_PRICE_RALLY_NOT_STAGE3 = "EVENT_PRICE_RALLY_NOT_STAGE3"
    POLICY_DIRECTIONALITY_ERROR = "POLICY_DIRECTIONALITY_ERROR"
    STRATEGIC_SUPPLY_CHAIN_EXPORT_CONTROL_EVENT = "STRATEGIC_SUPPLY_CHAIN_EXPORT_CONTROL_EVENT"
    EXPORT_CONTROL_TO_OFFTAKE_ESCALATION = "EXPORT_CONTROL_TO_OFFTAKE_ESCALATION"
    CLIMATE_DISASTER_EVENT = "CLIMATE_DISASTER_EVENT"
    CLIMATE_EVENT_TO_GRID_INFRA = "CLIMATE_EVENT_TO_GRID_INFRA"
    EVENT_DISEASE_PEST_DEMAND = "EVENT_DISEASE_PEST_DEMAND"
    GOVERNMENT_STOCKPILE_REVENUE_GUIDANCE = "GOVERNMENT_STOCKPILE_REVENUE_GUIDANCE"
    PUBLIC_HEALTH_PROCUREMENT_REVERSAL = "PUBLIC_HEALTH_PROCUREMENT_REVERSAL"
    DIAGNOSTICS_INFECTIOUS_EVENT = "DIAGNOSTICS_INFECTIOUS_EVENT"
    SPECULATIVE_SCIENCE_THEME = "SPECULATIVE_SCIENCE_THEME"
    ADVANCED_MATERIAL_SPECULATIVE_THEME = "ADVANCED_MATERIAL_SPECULATIVE_THEME"
    POLICY_LOCAL_THEME = "POLICY_LOCAL_THEME"
    INDUSTRIAL_POLICY_TARIFF_EVENT = "INDUSTRIAL_POLICY_TARIFF_EVENT"
    POLICY_MARKET_SHOCK_EVENT = "POLICY_MARKET_SHOCK_EVENT"
    STRUCTURAL_STAGE3_EARLY_CAPTURE = "STRUCTURAL_STAGE3_EARLY_CAPTURE"
    STAGE2_STRONG_NOT_GREEN = "STAGE2_STRONG_NOT_GREEN"
    CYCLE_SUCCESS_NOT_STRUCTURAL = "CYCLE_SUCCESS_NOT_STRUCTURAL"
    PRIVATE_OR_HOLDCO_LINK_CAP = "PRIVATE_OR_HOLDCO_LINK_CAP"
    OPERATIONAL_TRUST_HARD_4C = "OPERATIONAL_TRUST_HARD_4C"
    LEGAL_GOVERNANCE_4C_WATCH = "LEGAL_GOVERNANCE_4C_WATCH"
    POLICY_MARKET_SHOCK_OVERLAY = "POLICY_MARKET_SHOCK_OVERLAY"
    AGRI_MACHINERY_EXPORT_CYCLE_KOREA = "AGRI_MACHINERY_EXPORT_CYCLE_KOREA"
    AGRI_MACHINERY_AUTONOMOUS_ROBOT_OPTION = "AGRI_MACHINERY_AUTONOMOUS_ROBOT_OPTION"
    FERTILIZER_INPUT_PRICE_COST_KOREA = "FERTILIZER_INPUT_PRICE_COST_KOREA"
    LIVESTOCK_DISEASE_PRICE_EVENT_KOREA = "LIVESTOCK_DISEASE_PRICE_EVENT_KOREA"
    FEED_GRAIN_COST_PASS_THROUGH = "FEED_GRAIN_COST_PASS_THROUGH"
    TUNA_FISHERY_GLOBAL_BRAND_LEGAL_RISK = "TUNA_FISHERY_GLOBAL_BRAND_LEGAL_RISK"
    CONSUMER_REGULATED_PRODUCT_KOREA = "CONSUMER_REGULATED_PRODUCT_KOREA"
    HEATED_TOBACCO_GLOBAL_DISTRIBUTION = "HEATED_TOBACCO_GLOBAL_DISTRIBUTION"
    EDUCATION_POLICY_EVENT_KOREA = "EDUCATION_POLICY_EVENT_KOREA"
    EDTECH_AI_DISRUPTION_KOREA = "EDTECH_AI_DISRUPTION_KOREA"
    KIDS_IP_PLATFORM_KOREA = "KIDS_IP_PLATFORM_KOREA"
    SMART_FARM_UNIT_ECONOMICS_KOREA = "SMART_FARM_UNIT_ECONOMICS_KOREA"
    SERVICE_KIOSK_LOCAL_REGULATION_KOREA = "SERVICE_KIOSK_LOCAL_REGULATION_KOREA"
    COMMERCIAL_REAL_ESTATE_CREDIT = "COMMERCIAL_REAL_ESTATE_CREDIT"
    RESIDENTIAL_HOUSING_CYCLE = "RESIDENTIAL_HOUSING_CYCLE"
    AI_DATA_CENTER_REAL_ASSET_DEVELOPMENT = "AI_DATA_CENTER_REAL_ASSET_DEVELOPMENT"
    UTILITIES_REGULATED_TARIFF = "UTILITIES_REGULATED_TARIFF"
    HOLDING_RESTRUCTURING_GOVERNANCE = "HOLDING_RESTRUCTURING_GOVERNANCE"
    TURNAROUND_COST_RESTRUCTURING = "TURNAROUND_COST_RESTRUCTURING"
    ONE_OFF_EVENT_DEMAND = "ONE_OFF_EVENT_DEMAND"
    THEME_VALUATION_OVERHEAT = "THEME_VALUATION_OVERHEAT"
    K_FOOD_SINGLE_HERO_PRODUCT = "K_FOOD_SINGLE_HERO_PRODUCT"
    REDTEAM_ACCOUNTING_TRUST_OVERLAY = "REDTEAM_ACCOUNTING_TRUST_OVERLAY"
    AI_CAPEX_CROWDING_OVERLAY = "AI_CAPEX_CROWDING_OVERLAY"
    CIRCULAR_AI_FINANCING_OVERLAY = "CIRCULAR_AI_FINANCING_OVERLAY"
    FINANCIAL_REPORTING_INTEGRITY_RISK = "FINANCIAL_REPORTING_INTEGRITY_RISK"
    CHANNEL_STUFFING_INVENTORY_OVERLAY = "CHANNEL_STUFFING_INVENTORY_OVERLAY"
    TARIFF_IMPORT_REGULATION_OVERLAY = "TARIFF_IMPORT_REGULATION_OVERLAY"
    PRICE_ONLY_RALLY = "PRICE_ONLY_RALLY"
    EVENT_PREMIUM = "EVENT_PREMIUM"
    EVENT_TO_CONTRACT_ESCALATION = "EVENT_TO_CONTRACT_ESCALATION"
    CYCLICAL_SUCCESS = "CYCLICAL_SUCCESS"
    STRUCTURAL_SUCCESS_ALIGNED = "STRUCTURAL_SUCCESS_ALIGNED"
    STRUCTURAL_SUCCESS_BUT_4B_WATCH = "STRUCTURAL_SUCCESS_BUT_4B_WATCH"
    STAGE2_EVIDENCE_NOT_GREEN = "STAGE2_EVIDENCE_NOT_GREEN"
    SECTOR_SUCCESS_BUT_4B_WATCH = "SECTOR_SUCCESS_BUT_4B_WATCH"
    SECTOR_SUCCESS_BUT_POLICY_SHOCK_WATCH = "SECTOR_SUCCESS_BUT_POLICY_SHOCK_WATCH"
    EVIDENCE_GOOD_BUT_PRICE_FAILED = "EVIDENCE_GOOD_BUT_PRICE_FAILED"
    FALSE_POSITIVE_SCORE = "FALSE_POSITIVE_SCORE"
    CROWDED_RERATING_4B_WATCH = "CROWDED_RERATING_4B_WATCH"
    THESIS_BREAK_4C = "THESIS_BREAK_4C"
    LEGAL_REGULATORY_REDTEAM = "LEGAL_REGULATORY_REDTEAM"
    OPERATIONAL_TRUST_BREAK = "OPERATIONAL_TRUST_BREAK"
    LEVERAGE_FCF_BREAKDOWN = "LEVERAGE_FCF_BREAKDOWN"
    COMMERCIALIZATION_FAILURE = "COMMERCIALIZATION_FAILURE"
    AFFO_CASHFLOW_INTEGRITY_RISK = "AFFO_CASHFLOW_INTEGRITY_RISK"
    CAPEX_AFFO_DILUTION_RISK = "CAPEX_AFFO_DILUTION_RISK"
    STABLECOIN_CONVERTIBILITY_RISK = "STABLECOIN_CONVERTIBILITY_RISK"
    CIRCULAR_AI_FINANCING_WATCH = "CIRCULAR_AI_FINANCING_WATCH"
    DISCLOSURE_CONFIDENCE_CAP = "DISCLOSURE_CONFIDENCE_CAP"
    DISCLOSURE_CONFIDENCE_CAPPED = "DISCLOSURE_CONFIDENCE_CAPPED"
    UNKNOWN_INSUFFICIENT_EVIDENCE = "UNKNOWN_INSUFFICIENT_EVIDENCE"
    GENERIC_UNCLASSIFIED = "GENERIC_UNCLASSIFIED"


@dataclass(frozen=True)
class ArchetypeDefinition:
    """Lifecycle signals and future score-weight guidance for one archetype."""

    archetype: E2RArchetype
    stage1_radar_signals: tuple[str, ...]
    stage2_candidate_signals: tuple[str, ...]
    stage3_high_conviction_signals: tuple[str, ...]
    stage4a_ongoing_signals: tuple[str, ...]
    stage4b_graduation_overheat_signals: tuple[str, ...]
    stage4c_thesis_break_signals: tuple[str, ...]
    key_evidence_families: tuple[str, ...]
    false_positive_patterns: tuple[str, ...]
    preferred_score_weights: Mapping[str, float]


def _weights(
    *,
    eps_fcf: float,
    visibility: float,
    bottleneck: float,
    mispricing: float,
    valuation: float,
    confidence: float = 5.0,
) -> Mapping[str, float]:
    return {
        "eps_fcf_explosion": eps_fcf,
        "earnings_visibility": visibility,
        "bottleneck_pricing": bottleneck,
        "market_mispricing": mispricing,
        "valuation_rerating": valuation,
        "information_confidence": confidence,
    }


def _generic_definition(archetype: E2RArchetype) -> ArchetypeDefinition:
    return ArchetypeDefinition(
        archetype=archetype,
        stage1_radar_signals=("price/trading value breakout", "sector keyword appears", "company event disclosure"),
        stage2_candidate_signals=("reported OP/EPS acceleration", "research report confirmation", "valuation frame change"),
        stage3_high_conviction_signals=("multi-source evidence", "EPS/FCF bodyweight change", "old-frame mispricing"),
        stage4a_ongoing_signals=("evidence remains intact", "revision path remains positive"),
        stage4b_graduation_overheat_signals=("large rerating return", "crowded positive reports", "revision slowdown"),
        stage4c_thesis_break_signals=("estimate cuts", "margin reversal", "hard disclosure risk"),
        key_evidence_families=("price", "financial_actual", "research_report", "news"),
        false_positive_patterns=("single-source story", "theme-only runup", "no revision support"),
        preferred_score_weights=_weights(eps_fcf=20, visibility=20, bottleneck=15, mispricing=15, valuation=15),
    )


ARCHETYPE_DEFINITIONS: dict[E2RArchetype, ArchetypeDefinition] = {
    archetype: _generic_definition(archetype) for archetype in E2RArchetype
}

ARCHETYPE_DEFINITIONS.update(
    {
        E2RArchetype.CONTRACT_BACKLOG_INDUSTRIAL: ArchetypeDefinition(
            archetype=E2RArchetype.CONTRACT_BACKLOG_INDUSTRIAL,
            stage1_radar_signals=("supply contract disclosure", "backlog keyword", "price/trading value breakout"),
            stage2_candidate_signals=("contract_amount_to_prior_sales", "contract_duration_months", "backlog_to_sales", "OP/EPS revision"),
            stage3_high_conviction_signals=("multi-year order visibility", "capacity constraint", "ASP/pricing power", "EPS/FCF bodyweight change"),
            stage4a_ongoing_signals=("backlog remains high", "delivery/margin path intact", "revision path remains positive"),
            stage4b_graduation_overheat_signals=("multiple expansion", "revision slowdown", "universally bullish reports"),
            stage4c_thesis_break_signals=("contract cancellation", "backlog decline", "margin/ASP drop"),
            key_evidence_families=("disclosure", "research_report", "consensus_revision", "price"),
            false_positive_patterns=("small one-time contract", "low margin backlog", "valuation already saturated"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=24, bottleneck=22, mispricing=13, valuation=12),
        ),
        E2RArchetype.DEFENSE_GOVERNMENT_BACKLOG: ArchetypeDefinition(
            archetype=E2RArchetype.DEFENSE_GOVERNMENT_BACKLOG,
            stage1_radar_signals=("export defense contract", "government customer disclosure", "backlog keyword"),
            stage2_candidate_signals=("multi-year delivery schedule", "order backlog", "margin recovery", "target/EPS revision"),
            stage3_high_conviction_signals=("government-backed backlog", "export mix improvement", "delivery visibility", "EPS bodyweight change"),
            stage4a_ongoing_signals=("delivery schedule on track", "new orders continue", "margin path intact"),
            stage4b_graduation_overheat_signals=("crowded defense reports", "price outruns revision", "delivery risk ignored"),
            stage4c_thesis_break_signals=("delivery delay", "contract change", "cost overrun", "export approval issue"),
            key_evidence_families=("disclosure", "research_report", "financial_actual", "news"),
            false_positive_patterns=("headline contract without margin", "political delay", "single export customer risk"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=24, bottleneck=17, mispricing=14, valuation=12),
        ),
        E2RArchetype.EXPORT_RECURRING_CONSUMER: ArchetypeDefinition(
            archetype=E2RArchetype.EXPORT_RECURRING_CONSUMER,
            stage1_radar_signals=("export growth", "OPM surprise", "channel expansion"),
            stage2_candidate_signals=("FY1/FY2 EPS/OP revision", "export mix increase", "repeated overseas demand"),
            stage3_high_conviction_signals=("recurring demand", "channel expansion", "OPM leverage", "valuation below new frame"),
            stage4a_ongoing_signals=("sell-through remains strong", "new channels add revenue", "margin remains high"),
            stage4b_graduation_overheat_signals=("peak margin", "crowded reports", "decelerating sell-through"),
            stage4c_thesis_break_signals=("export slowdown", "channel inventory issue", "ASP/margin reversal"),
            key_evidence_families=("research_report", "financial_actual", "consensus_revision", "news"),
            false_positive_patterns=("short-lived product fad", "inventory stuffing", "FX-only margin lift"),
            preferred_score_weights=_weights(eps_fcf=22, visibility=23, bottleneck=14, mispricing=16, valuation=14),
        ),
        E2RArchetype.K_BEAUTY_EXPORT_DISTRIBUTION: ArchetypeDefinition(
            archetype=E2RArchetype.K_BEAUTY_EXPORT_DISTRIBUTION,
            stage1_radar_signals=("export growth", "platform/distribution expansion", "OPM/ROE improvement"),
            stage2_candidate_signals=("brand/customer diversification", "FY1/FY2 OP/EPS revision", "repeat orders"),
            stage3_high_conviction_signals=("recurring export channel", "platform scale", "margin leverage", "new valuation frame"),
            stage4a_ongoing_signals=("channel expansion continues", "brand breadth improves", "cash conversion remains healthy"),
            stage4b_graduation_overheat_signals=("single-platform crowding", "margin peak", "inventory risk ignored"),
            stage4c_thesis_break_signals=("export channel slowdown", "inventory spike", "platform fee/margin reversal"),
            key_evidence_families=("research_report", "financial_actual", "news", "consensus_revision"),
            false_positive_patterns=("single brand fad", "channel stuffing", "low-quality receivables growth"),
            preferred_score_weights=_weights(eps_fcf=22, visibility=23, bottleneck=13, mispricing=16, valuation=14),
        ),
        E2RArchetype.MEMORY_HBM_CAPACITY: ArchetypeDefinition(
            archetype=E2RArchetype.MEMORY_HBM_CAPACITY,
            stage1_radar_signals=("HBM demand", "memory price increase", "earnings turnaround"),
            stage2_candidate_signals=("consensus revision", "DRAM/NAND/HBM pricing", "supply discipline"),
            stage3_high_conviction_signals=("multi-year EPS path", "HBM/capacity bottleneck", "old cyclical discount removal"),
            stage4a_ongoing_signals=("prices and revisions remain positive", "capacity allocation holds", "customer demand intact"),
            stage4b_graduation_overheat_signals=("full rerating", "revision slowdown", "capex overbuild signs"),
            stage4c_thesis_break_signals=("customer capex collapse", "supply glut", "memory price decline"),
            key_evidence_families=("financial_actual", "research_report", "consensus_revision", "news"),
            false_positive_patterns=("pure cyclical bounce", "price-only memory rally", "capex overbuild ignored"),
            preferred_score_weights=_weights(eps_fcf=24, visibility=21, bottleneck=19, mispricing=15, valuation=12),
        ),
        E2RArchetype.AUTO_MOBILITY_COMPLETED_VEHICLE: ArchetypeDefinition(
            archetype=E2RArchetype.AUTO_MOBILITY_COMPLETED_VEHICLE,
            stage1_radar_signals=("hybrid mix improvement", "shareholder return", "export mix", "EV slowdown response"),
            stage2_candidate_signals=("OP/FCF stability", "ROE/PBR rerating", "buyback or dividend execution"),
            stage3_high_conviction_signals=("FCF supports recurring return", "high-margin mix persists", "old auto discount removed"),
            stage4a_ongoing_signals=("mix and FCF remain strong", "return policy continues"),
            stage4b_graduation_overheat_signals=("value-up narrative crowded", "peak margin ignored", "tariff risk ignored"),
            stage4c_thesis_break_signals=("tariff hit", "recall cost", "demand slowdown", "peak margin reversal"),
            key_evidence_families=("financial_actual", "research_report", "news", "price"),
            false_positive_patterns=("buyback headline without FCF", "one-quarter sales mix", "policy headline only"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=18, bottleneck=10, mispricing=15, valuation=17),
        ),
        E2RArchetype.AUTO_US_LOCALIZATION_LABOR_VISA_RISK: ArchetypeDefinition(
            archetype=E2RArchetype.AUTO_US_LOCALIZATION_LABOR_VISA_RISK,
            stage1_radar_signals=("US localization", "factory ramp-up", "tariff mitigation plan"),
            stage2_candidate_signals=("local production ramp", "labor plan", "visa process stable"),
            stage3_high_conviction_signals=("not applicable; RedTeam overlay for localization execution risk",),
            stage4a_ongoing_signals=("ramp and labor availability remain stable",),
            stage4b_graduation_overheat_signals=("localization benefit priced before ramp proof",),
            stage4c_thesis_break_signals=("ramp-up delay", "skilled labor shortage", "visa delay", "labor dispute"),
            key_evidence_families=("news", "disclosure", "financial_actual"),
            false_positive_patterns=("localization treated as margin recovery before ramp proof",),
            preferred_score_weights=_weights(eps_fcf=0, visibility=0, bottleneck=0, mispricing=0, valuation=0),
        ),
        E2RArchetype.AUTO_MOBILITY_COMPONENTS: ArchetypeDefinition(
            archetype=E2RArchetype.AUTO_MOBILITY_COMPONENTS,
            stage1_radar_signals=("auto parts order", "ADAS or EV component", "high-value lighting or electronics"),
            stage2_candidate_signals=("customer diversification", "cost pass-through", "OP/EPS revision", "raw-material stability"),
            stage3_high_conviction_signals=("repeat program visibility", "margin stable", "quality cost low"),
            stage4a_ongoing_signals=("customer mix broadens", "margin and quality costs remain controlled"),
            stage4b_graduation_overheat_signals=("component group rerating crowded", "single customer risk ignored"),
            stage4c_thesis_break_signals=("customer program cut", "quality recall", "raw-material squeeze", "OEM pressure"),
            key_evidence_families=("financial_actual", "research_report", "news", "price"),
            false_positive_patterns=("single OEM order treated as structural", "component theme without margin proof"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=17, bottleneck=10, mispricing=14, valuation=14),
        ),
        E2RArchetype.TIRE_AUTO_COMPONENT_SPREAD: ArchetypeDefinition(
            archetype=E2RArchetype.TIRE_AUTO_COMPONENT_SPREAD,
            stage1_radar_signals=("tire demand recovery", "raw-material spread", "replacement tire demand"),
            stage2_candidate_signals=("OE/RE mix improves", "OP/EPS revision", "North America demand stable"),
            stage3_high_conviction_signals=("spread and FCF persist", "China competition controlled"),
            stage4a_ongoing_signals=("replacement demand and margin remain healthy",),
            stage4b_graduation_overheat_signals=("spread peak ignored", "auto cycle fully priced"),
            stage4c_thesis_break_signals=("North America demand slowdown", "raw-material spike", "tariff hit", "vehicle sales slowdown"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("auto sales recovery treated as tire margin proof", "raw-material spread is one-off"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=13, bottleneck=12, mispricing=11, valuation=10),
        ),
        E2RArchetype.AIRLINE_TRAVEL_CYCLE: ArchetypeDefinition(
            archetype=E2RArchetype.AIRLINE_TRAVEL_CYCLE,
            stage1_radar_signals=("passenger recovery", "cargo rate", "airline merger", "reopening news"),
            stage2_candidate_signals=("revenue/OP improvement", "integration synergy", "passenger cargo mix"),
            stage3_high_conviction_signals=("FCF and cost stability verified", "fuel/FX risk controlled"),
            stage4a_ongoing_signals=("load factor and yield remain strong", "fuel/FX manageable"),
            stage4b_graduation_overheat_signals=("reopening or integration synergy crowded", "oil/FX risk ignored"),
            stage4c_thesis_break_signals=("fuel shock", "FX loss", "integration cost", "cargo/passenger slowdown"),
            key_evidence_families=("financial_actual", "research_report", "news", "price"),
            false_positive_patterns=("traffic recovery without margin", "policy or merger headline only"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=14, bottleneck=5, mispricing=12, valuation=10),
        ),
        E2RArchetype.CASINO_DUTYFREE_TOURISM: ArchetypeDefinition(
            archetype=E2RArchetype.CASINO_DUTYFREE_TOURISM,
            stage1_radar_signals=("visa policy", "tourist arrival recovery", "casino/duty-free policy news"),
            stage2_candidate_signals=("tourist spend", "drop amount", "duty-free sales", "hotel occupancy", "OP leverage"),
            stage3_high_conviction_signals=("visitor mix improves", "China dependence lower", "cash flow and margin visible"),
            stage4a_ongoing_signals=("tourist spend and OPM remain strong",),
            stage4b_graduation_overheat_signals=("tourism policy rally crowded", "policy event priced before spend"),
            stage4c_thesis_break_signals=("visitor mix weak", "duty-free ASP weak", "casino drop slowdown", "CAPEX burden"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("visa news treated as spend proof", "tourist count without margin"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=13, bottleneck=5, mispricing=12, valuation=10),
        ),
        E2RArchetype.TOURISM_POLICY_EVENT: ArchetypeDefinition(
            archetype=E2RArchetype.TOURISM_POLICY_EVENT,
            stage1_radar_signals=("visa policy", "tourism policy", "group-tour reopening"),
            stage2_candidate_signals=("tourist arrivals", "visitor spend", "drop amount", "duty-free sales"),
            stage3_high_conviction_signals=("policy converts to OPM/FCF", "visitor mix and spend verified"),
            stage4a_ongoing_signals=("spend and margins remain visible after policy event",),
            stage4b_graduation_overheat_signals=("tourism policy rally crowded", "price moves before spend evidence"),
            stage4c_thesis_break_signals=("tourist spend disappoints", "duty-free ASP weak", "casino drop weak"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("visa headline treated as earnings", "arrival count without spend"),
            preferred_score_weights=_weights(eps_fcf=8, visibility=7, bottleneck=4, mispricing=10, valuation=6),
        ),
        E2RArchetype.SHIPPING_FREIGHT_CYCLE: ArchetypeDefinition(
            archetype=E2RArchetype.SHIPPING_FREIGHT_CYCLE,
            stage1_radar_signals=("freight rate spike", "Red Sea disruption", "vessel capacity adjustment"),
            stage2_candidate_signals=("rate index improves", "EBITDA improves", "dividend or cash flow rises"),
            stage3_high_conviction_signals=("structural Green is restricted unless multi-year supply discipline is proven",),
            stage4a_ongoing_signals=("rates and cash flow remain above cycle floor",),
            stage4b_graduation_overheat_signals=("freight peak", "shipping stocks crowded", "supply risk ignored"),
            stage4c_thesis_break_signals=("freight rate collapse", "overcapacity", "new ship delivery", "route normalization", "earnings collapse"),
            key_evidence_families=("price", "financial_actual", "research_report", "news"),
            false_positive_patterns=("spot freight spike annualized", "temporary disruption treated as structural"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=8, bottleneck=18, mispricing=8, valuation=8),
        ),
        E2RArchetype.MOBILITY_RENTAL_MICROMOBILITY: ArchetypeDefinition(
            archetype=E2RArchetype.MOBILITY_RENTAL_MICROMOBILITY,
            stage1_radar_signals=("IPO filing", "city expansion", "ridership growth", "fleet expansion"),
            stage2_candidate_signals=("revenue growth", "FCF positive", "unit economics", "utilization rate"),
            stage3_high_conviction_signals=("recurring usage", "FCF and debt stability", "regulatory risk controlled"),
            stage4a_ongoing_signals=("utilization and FCF remain positive",),
            stage4b_graduation_overheat_signals=("IPO valuation crowded", "growth priced before profitability"),
            stage4c_thesis_break_signals=("debt maturity", "regulatory restriction", "seasonality loss", "repair cost spike"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("user growth without unit economics", "fleet growth with cash burn"),
            preferred_score_weights=_weights(eps_fcf=17, visibility=14, bottleneck=6, mispricing=12, valuation=10),
        ),
        E2RArchetype.URBAN_AIR_DRONE: ArchetypeDefinition(
            archetype=E2RArchetype.URBAN_AIR_DRONE,
            stage1_radar_signals=("Part 135", "strategic investment", "eVTOL policy", "air-taxi partnership"),
            stage2_candidate_signals=("type certification", "production certification", "commercial operation", "customer contract"),
            stage3_high_conviction_signals=("commercial revenue", "unit economics", "cash runway secure"),
            stage4a_ongoing_signals=("certification and production remain on schedule",),
            stage4b_graduation_overheat_signals=("pre-revenue valuation crowded", "certification risk ignored"),
            stage4c_thesis_break_signals=("certification delay", "cash burn", "discounted offering", "production delay"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("certification step treated as full commercialization", "theme rally before revenue"),
            preferred_score_weights=_weights(eps_fcf=10, visibility=10, bottleneck=6, mispricing=12, valuation=7),
        ),
        E2RArchetype.PART135_NOT_TYPE_CERTIFICATION: ArchetypeDefinition(
            archetype=E2RArchetype.PART135_NOT_TYPE_CERTIFICATION,
            stage1_radar_signals=("Part 135 approval", "operator certificate", "air-taxi launch plan"),
            stage2_candidate_signals=("type certification", "production certification", "commercial revenue"),
            stage3_high_conviction_signals=("not applicable; Part 135 alone is not Stage 3 proof",),
            stage4a_ongoing_signals=("certification path remains intact",),
            stage4b_graduation_overheat_signals=("Part 135 milestone overpriced before aircraft certification",),
            stage4c_thesis_break_signals=("type certification missing", "cash burn", "discounted offering", "production delay"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("operator certification confused with aircraft commercialization",),
            preferred_score_weights=_weights(eps_fcf=0, visibility=0, bottleneck=0, mispricing=0, valuation=0),
        ),
        E2RArchetype.AV_CRASH_DISCLOSURE_PROBE_OVERLAY: ArchetypeDefinition(
            archetype=E2RArchetype.AV_CRASH_DISCLOSURE_PROBE_OVERLAY,
            stage1_radar_signals=("AV crash report", "NHTSA preliminary evaluation", "remote assistance disclosure"),
            stage2_candidate_signals=("crash count quantified", "operational change after incident", "software fix confirmed"),
            stage3_high_conviction_signals=("not applicable; crash/probe evidence is a RedTeam overlay",),
            stage4a_ongoing_signals=("incident remediation remains transparent",),
            stage4b_graduation_overheat_signals=("AV deployment priced while crash probe unresolved",),
            stage4c_thesis_break_signals=("NHTSA probe", "crash reports", "remote assistance dependence", "hazard response failure"),
            key_evidence_families=("news", "regulatory", "disclosure"),
            false_positive_patterns=("deployment headline ignores safety probe",),
            preferred_score_weights=_weights(eps_fcf=0, visibility=0, bottleneck=0, mispricing=0, valuation=0),
        ),
        E2RArchetype.AUTONOMOUS_TRUCKING_PAID_FREIGHT_MILESTONE: ArchetypeDefinition(
            archetype=E2RArchetype.AUTONOMOUS_TRUCKING_PAID_FREIGHT_MILESTONE,
            stage1_radar_signals=("driverless trucking pilot", "freight customer announcement", "route launch"),
            stage2_candidate_signals=("paid freight", "driverless miles", "customer route", "carrier partner"),
            stage3_high_conviction_signals=("repeat customer", "fleet utilization", "cost per mile", "insurance cost stable"),
            stage4a_ongoing_signals=("paid miles expand across routes", "unit economics improve"),
            stage4b_graduation_overheat_signals=("paid freight milestone priced as scaled autonomy",),
            stage4c_thesis_break_signals=("tiny fleet", "restricted ODD", "negative FCF", "remote support cost spike"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("one route treated as full network", "paid milestone without margin evidence"),
            preferred_score_weights=_weights(eps_fcf=17, visibility=17, bottleneck=10, mispricing=14, valuation=9),
        ),
        E2RArchetype.SATELLITE_CONNECTIVITY_INFRA: ArchetypeDefinition(
            archetype=E2RArchetype.SATELLITE_CONNECTIVITY_INFRA,
            stage1_radar_signals=("airline connectivity contract", "secure communications", "satellite backlog"),
            stage2_candidate_signals=("connectivity revenue growth", "airline contract count", "EBITDA improvement", "backlog"),
            stage3_high_conviction_signals=("recurring connectivity revenue", "gross backlog", "debt/capex manageable"),
            stage4a_ongoing_signals=("contracts convert to revenue", "backlog remains visible"),
            stage4b_graduation_overheat_signals=("satellite connectivity narrative crowded", "debt/capex ignored"),
            stage4c_thesis_break_signals=("launch delay", "contract cancellation", "capex/debt stress", "competitor constellation pressure"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("space theme without contract", "backlog without cash conversion"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=20, bottleneck=10, mispricing=13, valuation=11),
        ),
        E2RArchetype.ONE_OFF_EVENT_DEMAND: ArchetypeDefinition(
            archetype=E2RArchetype.ONE_OFF_EVENT_DEMAND,
            stage1_radar_signals=("explosive temporary demand", "one-time supply shock", "pandemic/event keyword"),
            stage2_candidate_signals=("short-term EPS spike", "news volume spike", "price breakout"),
            stage3_high_conviction_signals=("normally not Green unless recurrence is proven",),
            stage4a_ongoing_signals=("temporary demand persists longer than expected",),
            stage4b_graduation_overheat_signals=("peak margins", "consensus extrapolates one-off demand"),
            stage4c_thesis_break_signals=("normalization", "ASP collapse", "demand cliff"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("one-off demand treated as structural", "temporary margin annualized"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=8, bottleneck=8, mispricing=8, valuation=8),
        ),
        E2RArchetype.THEME_VALUATION_OVERHEAT: ArchetypeDefinition(
            archetype=E2RArchetype.THEME_VALUATION_OVERHEAT,
            stage1_radar_signals=("theme keyword spike", "price-only breakout", "retail/crowding signal"),
            stage2_candidate_signals=("requires real estimates or official evidence; otherwise remains watch"),
            stage3_high_conviction_signals=("normally blocked without evidence-backed EPS/FCF path",),
            stage4a_ongoing_signals=("theme evidence remains but valuation is watched"),
            stage4b_graduation_overheat_signals=("return multiple excessive", "reports universally bullish", "valuation saturated"),
            stage4c_thesis_break_signals=("funding/dilution", "estimate cuts", "theme unwind"),
            key_evidence_families=("price", "news", "research_report"),
            false_positive_patterns=("story-only rerating", "no cash flow", "dilution ignored"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=8, bottleneck=8, mispricing=7, valuation=5),
        ),
        E2RArchetype.AI_DATA_CENTER_INFRASTRUCTURE: ArchetypeDefinition(
            archetype=E2RArchetype.AI_DATA_CENTER_INFRASTRUCTURE,
            stage1_radar_signals=("AI data center power demand", "grid bottleneck", "server/rack order keyword"),
            stage2_candidate_signals=("confirmed orders", "capacity constraint", "OP/EPS revision"),
            stage3_high_conviction_signals=("multi-source data-center demand", "power/cooling bottleneck", "EPS/FCF bodyweight change"),
            stage4a_ongoing_signals=("orders convert to revenue", "capacity remains scarce", "revision path intact"),
            stage4b_graduation_overheat_signals=("AI infrastructure narrative crowded", "price outruns orders", "capex slowdown hints"),
            stage4c_thesis_break_signals=("customer capex cut", "order cancellation", "margin pressure"),
            key_evidence_families=("disclosure", "research_report", "news", "consensus_revision"),
            false_positive_patterns=("AI keyword only", "no confirmed order", "power theme without revenue"),
            preferred_score_weights=_weights(eps_fcf=22, visibility=22, bottleneck=21, mispricing=13, valuation=12),
        ),
        E2RArchetype.NUCLEAR_SMR_GRID_POLICY: ArchetypeDefinition(
            archetype=E2RArchetype.NUCLEAR_SMR_GRID_POLICY,
            stage1_radar_signals=("nuclear policy event", "SMR/grid contract keyword", "export project news"),
            stage2_candidate_signals=("contract award", "permitted project timeline", "supplier revenue visibility"),
            stage3_high_conviction_signals=("binding project economics", "multi-year backlog", "EPS/FCF path confirmed"),
            stage4a_ongoing_signals=("project schedule intact", "policy support intact"),
            stage4b_graduation_overheat_signals=("policy premium crowds valuation", "legal delay ignored"),
            stage4c_thesis_break_signals=("legal delay", "project cancellation", "cost overrun"),
            key_evidence_families=("disclosure", "news", "research_report"),
            false_positive_patterns=("policy headline without contract", "legal appeal ignored"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=24, bottleneck=14, mispricing=15, valuation=12),
        ),
        E2RArchetype.VALUE_UP_SHAREHOLDER_RETURN: ArchetypeDefinition(
            archetype=E2RArchetype.VALUE_UP_SHAREHOLDER_RETURN,
            stage1_radar_signals=("buyback/cancellation", "dividend policy", "value-up disclosure"),
            stage2_candidate_signals=("ROE improvement", "capital return durability", "NAV discount narrowing catalyst"),
            stage3_high_conviction_signals=("repeatable cash return", "governance improvement", "earnings/NAV support"),
            stage4a_ongoing_signals=("capital return continues", "balance sheet remains healthy"),
            stage4b_graduation_overheat_signals=("event premium fully priced", "return policy no longer incremental"),
            stage4c_thesis_break_signals=("buyback without cancellation", "governance dispute", "credit deterioration"),
            key_evidence_families=("disclosure", "financial_actual", "news", "research_report"),
            false_positive_patterns=("announcement-only premium", "no FCF/NAV improvement", "one-off event"),
            preferred_score_weights=_weights(eps_fcf=16, visibility=19, bottleneck=8, mispricing=24, valuation=20),
        ),
        E2RArchetype.GOVERNMENT_AI_PROGRAM_OF_RECORD: ArchetypeDefinition(
            archetype=E2RArchetype.GOVERNMENT_AI_PROGRAM_OF_RECORD,
            stage1_radar_signals=("government AI pilot", "defense AI software", "public-sector AI contract"),
            stage2_candidate_signals=("program of record", "multi-year budget", "official procurement", "long-term contract"),
            stage3_high_conviction_signals=("recurring government software revenue", "commercial expansion", "auditable workflow"),
            stage4a_ongoing_signals=("program funding and commercial expansion remain intact",),
            stage4b_graduation_overheat_signals=("government AI contractor premium crowded", "valuation saturated"),
            stage4c_thesis_break_signals=("budget cut", "contract cancellation", "audit failure", "political risk"),
            key_evidence_families=("disclosure", "financial_actual", "news", "research_report"),
            false_positive_patterns=("pilot treated as program of record", "government concentration risk ignored"),
            preferred_score_weights=_weights(eps_fcf=23, visibility=24, bottleneck=11, mispricing=15, valuation=10),
        ),
        E2RArchetype.CLOUD_AI_SOFTWARE_INFRA: ArchetypeDefinition(
            archetype=E2RArchetype.CLOUD_AI_SOFTWARE_INFRA,
            stage1_radar_signals=("cloud ERP transition", "B2B SaaS expansion", "AI workflow feature"),
            stage2_candidate_signals=("ARR growth", "recurring revenue", "customer retention", "OPM improvement"),
            stage3_high_conviction_signals=("customer lock-in", "FCF conversion", "net retention", "old software-frame rerating"),
            stage4a_ongoing_signals=("ARR and retention remain strong", "FCF conversion continues"),
            stage4b_graduation_overheat_signals=("AI SaaS narrative crowded", "valuation saturation"),
            stage4c_thesis_break_signals=("churn spike", "AI compute cost surge", "OPM decline", "services revenue reversion"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("AI feature only", "SI-like revenue mistaken for SaaS", "retention not verified"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=23, bottleneck=8, mispricing=16, valuation=14),
        ),
        E2RArchetype.LEGACY_SAAS_AI_REINFORCEMENT: ArchetypeDefinition(
            archetype=E2RArchetype.LEGACY_SAAS_AI_REINFORCEMENT,
            stage1_radar_signals=("AI agent launch", "copilot launch", "workflow AI feature"),
            stage2_candidate_signals=("AI ARR", "attach rate", "customer adoption", "productivity ROI"),
            stage3_high_conviction_signals=("seat churn low", "workflow lock-in stronger", "gross margin stable", "FCF conversion"),
            stage4a_ongoing_signals=("AI attach grows without seat downsell",),
            stage4b_graduation_overheat_signals=("AI agent narrative priced before ARR scale",),
            stage4c_thesis_break_signals=("license downsell", "gross margin pressure", "agent cost overrun", "workflow lock-in failure"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("AI feature treated as ARR", "agent revenue too small for multiple", "seat churn ignored"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=21, bottleneck=8, mispricing=14, valuation=11),
        ),
        E2RArchetype.AI_SOFTWARE_APPLICATION: ArchetypeDefinition(
            archetype=E2RArchetype.AI_SOFTWARE_APPLICATION,
            stage1_radar_signals=("AI application launch", "enterprise adoption headline", "API usage growth"),
            stage2_candidate_signals=("paid customer growth", "API revenue", "workflow integration", "gross margin visibility"),
            stage3_high_conviction_signals=("repeat paid usage", "FCF conversion", "compute cost controlled"),
            stage4a_ongoing_signals=("paid usage expands", "unit economics remain healthy"),
            stage4b_graduation_overheat_signals=("AI app narrative crowded", "valuation before margin proof"),
            stage4c_thesis_break_signals=("compute cost spike", "model dependency", "copyright or data lawsuit"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("AI label without paid usage", "free user growth mistaken for revenue"),
            preferred_score_weights=_weights(eps_fcf=19, visibility=18, bottleneck=9, mispricing=15, valuation=13),
        ),
        E2RArchetype.GAME_CONTENT_IP: ArchetypeDefinition(
            archetype=E2RArchetype.GAME_CONTENT_IP,
            stage1_radar_signals=("new title announcement", "IP expansion", "platform user growth"),
            stage2_candidate_signals=("bookings growth", "sell-through", "live-service monetization", "OP/EPS revision"),
            stage3_high_conviction_signals=("repeat IP portfolio", "global monetization", "low single-title risk"),
            stage4a_ongoing_signals=("bookings and live service remain strong", "pipeline executes"),
            stage4b_graduation_overheat_signals=("single IP valuation crowded", "launch expectations saturated"),
            stage4c_thesis_break_signals=("title delay", "bookings guide cut", "child safety regulation", "user growth slowdown"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("pre-release hype", "single-title dependency", "user growth without monetization"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=18, bottleneck=6, mispricing=14, valuation=12),
        ),
        E2RArchetype.MEDIA_AD_CONTENT_CYCLE: ArchetypeDefinition(
            archetype=E2RArchetype.MEDIA_AD_CONTENT_CYCLE,
            stage1_radar_signals=("ad market recovery", "CTV growth", "digital ad rebound"),
            stage2_candidate_signals=("ad revenue growth", "ARPU improvement", "OPM improvement"),
            stage3_high_conviction_signals=("repeat platform ad revenue", "hybrid subscription/ad model", "budget resilience"),
            stage4a_ongoing_signals=("ad revenue and ARPU remain strong",),
            stage4b_graduation_overheat_signals=("ad-tech valuation crowded", "growth expectations saturated"),
            stage4c_thesis_break_signals=("client budget cut", "revenue miss", "privacy lawsuit", "scam ad regulation"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("cyclical ad rebound treated as structural", "privacy risk ignored"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=16, bottleneck=6, mispricing=14, valuation=12),
        ),
        E2RArchetype.SECURITY_IDENTITY_DEEPFAKE: ArchetypeDefinition(
            archetype=E2RArchetype.SECURITY_IDENTITY_DEEPFAKE,
            stage1_radar_signals=("cybersecurity demand", "identity threat", "deepfake regulation"),
            stage2_candidate_signals=("ARR growth", "customer diversification", "low churn", "OPM improvement"),
            stage3_high_conviction_signals=("security platform lock-in", "renewal strength", "operational trust intact"),
            stage4a_ongoing_signals=("renewals and trust remain strong",),
            stage4b_graduation_overheat_signals=("security valuation crowded", "incident risk ignored"),
            stage4c_thesis_break_signals=("global outage", "customer lawsuit", "renewal risk", "trust damage"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("threat narrative without revenue", "operational trust risk ignored"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=20, bottleneck=10, mispricing=14, valuation=13),
        ),
        E2RArchetype.CYBERSECURITY_AI_THREAT_DEMAND: ArchetypeDefinition(
            archetype=E2RArchetype.CYBERSECURITY_AI_THREAT_DEMAND,
            stage1_radar_signals=("AI ransomware", "AI-driven cyber threat", "security budget increase"),
            stage2_candidate_signals=("billings growth", "ARR growth", "guidance raise", "renewal stability"),
            stage3_high_conviction_signals=("platform consolidation", "renewal strength", "operational trust intact", "FCF conversion"),
            stage4a_ongoing_signals=("billings, renewals, and operational trust remain strong",),
            stage4b_graduation_overheat_signals=("AI security narrative crowded", "incident risk ignored"),
            stage4c_thesis_break_signals=("global outage", "customer lawsuit", "renewal risk", "trust damage"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("threat narrative without billings", "security demand bubble", "outage risk ignored"),
            preferred_score_weights=_weights(eps_fcf=21, visibility=21, bottleneck=10, mispricing=14, valuation=11),
        ),
        E2RArchetype.BIOTECH_ROYALTY_COMMERCIALIZATION: ArchetypeDefinition(
            archetype=E2RArchetype.BIOTECH_ROYALTY_COMMERCIALIZATION,
            stage1_radar_signals=("royalty deal", "commercial launch", "milestone payment"),
            stage2_candidate_signals=("royalty economics", "partner launch progress", "cash runway"),
            stage3_high_conviction_signals=("commercial royalty visibility", "repeatable milestone/royalty path", "dilution risk controlled"),
            stage4a_ongoing_signals=("launch curve intact", "partner execution intact"),
            stage4b_graduation_overheat_signals=("royalty curve fully priced", "trial/news crowding"),
            stage4c_thesis_break_signals=("trial failure", "label/commercial setback", "CB/dilution pressure"),
            key_evidence_families=("disclosure", "news", "research_report"),
            false_positive_patterns=("pre-revenue story treated as cash flow", "dilution ignored"),
            preferred_score_weights=_weights(eps_fcf=15, visibility=23, bottleneck=9, mispricing=18, valuation=12),
        ),
        E2RArchetype.CDMO_HEALTHCARE_CONTRACT: ArchetypeDefinition(
            archetype=E2RArchetype.CDMO_HEALTHCARE_CONTRACT,
            stage1_radar_signals=("CDMO contract", "capacity utilization", "new plant validation"),
            stage2_candidate_signals=("multi-year manufacturing order", "utilization ramp", "margin path"),
            stage3_high_conviction_signals=("contracted capacity", "utilization leverage", "FCF path"),
            stage4a_ongoing_signals=("utilization and order intake remain strong",),
            stage4b_graduation_overheat_signals=("capacity priced before utilization", "customer concentration ignored"),
            stage4c_thesis_break_signals=("underutilization", "contract delay", "quality issue"),
            key_evidence_families=("disclosure", "financial_actual", "research_report"),
            false_positive_patterns=("capacity exists but demand absent", "validation delay"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=24, bottleneck=16, mispricing=14, valuation=12),
        ),
        E2RArchetype.CRO_CLINICAL_SERVICE: ArchetypeDefinition(
            archetype=E2RArchetype.CRO_CLINICAL_SERVICE,
            stage1_radar_signals=("clinical service backlog", "pharma R&D budget", "trial volume growth"),
            stage2_candidate_signals=("repeat clinical-service revenue", "customer diversification", "OP/EPS improvement"),
            stage3_high_conviction_signals=("multi-year service backlog", "funding cycle stable", "high FCF conversion"),
            stage4a_ongoing_signals=("backlog converts to revenue", "customer funding remains healthy"),
            stage4b_graduation_overheat_signals=("CRO recovery priced before backlog", "valuation multiple crowded"),
            stage4c_thesis_break_signals=("biotech funding crunch", "customer R&D budget cut", "forecast cut"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("R&D cycle headline without orders", "low-margin backlog", "customer budget cliff"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=20, bottleneck=8, mispricing=12, valuation=12),
        ),
        E2RArchetype.CRO_FUNDING_CYCLE_OVERLAY: ArchetypeDefinition(
            archetype=E2RArchetype.CRO_FUNDING_CYCLE_OVERLAY,
            stage1_radar_signals=("biotech funding crunch", "pharma R&D budget cut", "trial delay"),
            stage2_candidate_signals=("forecast cut", "customer budget pressure", "order cancellation risk"),
            stage3_high_conviction_signals=("not a Green source; overlay only"),
            stage4a_ongoing_signals=("customer funding remains stable",),
            stage4b_graduation_overheat_signals=("CRO recovery priced while funding cycle is weak",),
            stage4c_thesis_break_signals=("forecast cut", "customer budget cut", "trial delay", "revenue decline"),
            key_evidence_families=("financial_actual", "news", "research_report"),
            false_positive_patterns=("service backlog treated as durable while funding is shrinking",),
            preferred_score_weights=_weights(eps_fcf=0, visibility=0, bottleneck=0, mispricing=0, valuation=0),
        ),
        E2RArchetype.BIOSIMILAR_COMMERCIALIZATION: ArchetypeDefinition(
            archetype=E2RArchetype.BIOSIMILAR_COMMERCIALIZATION,
            stage1_radar_signals=("biosimilar approval", "patent expiry", "commercial launch news"),
            stage2_candidate_signals=("PBM or reimbursement listing", "prescription conversion", "launch revenue"),
            stage3_high_conviction_signals=("prescription growth", "margin defense", "multi-market launch"),
            stage4a_ongoing_signals=("launch curve intact", "pricing remains disciplined"),
            stage4b_graduation_overheat_signals=("approval headline fully priced", "biosimilar launch crowded"),
            stage4c_thesis_break_signals=("price competition", "prescription conversion delay", "margin collapse"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("approval treated as revenue", "PBM access missing", "price erosion ignored"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=20, bottleneck=6, mispricing=13, valuation=11),
        ),
        E2RArchetype.BIOSIMILAR_PBM_FORMULARY_SWITCH: ArchetypeDefinition(
            archetype=E2RArchetype.BIOSIMILAR_PBM_FORMULARY_SWITCH,
            stage1_radar_signals=("PBM formulary switch", "zero-copay program", "preferred drug list"),
            stage2_candidate_signals=("PBM listing", "prescription conversion", "margin defense"),
            stage3_high_conviction_signals=("sustained prescription share gain", "payer access scaled", "launch revenue conversion"),
            stage4a_ongoing_signals=("prescription conversion and margin remain intact",),
            stage4b_graduation_overheat_signals=("PBM headline priced before scripts",),
            stage4c_thesis_break_signals=("PBM exclusion", "rebate defense", "margin compression", "slow switching"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("formulary headline without prescriptions", "discount without margin defense"),
            preferred_score_weights=_weights(eps_fcf=17, visibility=17, bottleneck=6, mispricing=12, valuation=9),
        ),
        E2RArchetype.OBESITY_GLP1_COMMERCIALIZATION: ArchetypeDefinition(
            archetype=E2RArchetype.OBESITY_GLP1_COMMERCIALIZATION,
            stage1_radar_signals=("GLP-1 approval", "obesity drug prescription growth", "oral GLP-1 trial result"),
            stage2_candidate_signals=("weekly prescriptions", "insurance coverage", "supply capacity", "sales ramp"),
            stage3_high_conviction_signals=("durable prescription growth", "price defense", "OP/EPS revision"),
            stage4a_ongoing_signals=("prescriptions and supply remain strong", "coverage expands"),
            stage4b_graduation_overheat_signals=("obesity market narrative crowded", "valuation runs ahead of scripts"),
            stage4c_thesis_break_signals=("price cut", "compounded alternative", "coverage denial", "prescription slowdown"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("market size story without uptake", "competition ignored", "coverage assumed"),
            preferred_score_weights=_weights(eps_fcf=22, visibility=20, bottleneck=12, mispricing=13, valuation=12),
        ),
        E2RArchetype.ORAL_GLP1_APPROVAL_COMMERCIALIZATION: ArchetypeDefinition(
            archetype=E2RArchetype.ORAL_GLP1_APPROVAL_COMMERCIALIZATION,
            stage1_radar_signals=("oral GLP-1 approval", "self-pay price", "launch plan"),
            stage2_candidate_signals=("weekly scripts", "insurance coverage", "repeat refills", "sales ramp"),
            stage3_high_conviction_signals=("durable scripts", "price defense", "OP/EPS revision", "coverage expansion"),
            stage4a_ongoing_signals=("scripts, coverage, and refills remain strong",),
            stage4b_graduation_overheat_signals=("oral GLP-1 TAM priced before refills",),
            stage4c_thesis_break_signals=("scripts missing", "coverage gap", "price competition", "adherence failure"),
            key_evidence_families=("financial_actual", "news", "research_report"),
            false_positive_patterns=("approval treated as durable revenue", "TAM assumed without scripts"),
            preferred_score_weights=_weights(eps_fcf=21, visibility=19, bottleneck=11, mispricing=13, valuation=9),
        ),
        E2RArchetype.GENE_THERAPY_RARE_DISEASE: ArchetypeDefinition(
            archetype=E2RArchetype.GENE_THERAPY_RARE_DISEASE,
            stage1_radar_signals=("gene therapy approval", "rare disease unmet need", "patient recruitment"),
            stage2_candidate_signals=("treated patients", "reimbursement", "commercial sales"),
            stage3_high_conviction_signals=("repeat commercial uptake", "cash runway", "dilution risk controlled"),
            stage4a_ongoing_signals=("uptake and reimbursement remain intact",),
            stage4b_graduation_overheat_signals=("approval news priced as full commercialization",),
            stage4c_thesis_break_signals=("slow uptake", "cash crunch", "going concern", "dilutive financing"),
            key_evidence_families=("news", "financial_actual", "research_report"),
            false_positive_patterns=("approval without commercialization", "patient access friction", "cash burn ignored"),
            preferred_score_weights=_weights(eps_fcf=8, visibility=12, bottleneck=8, mispricing=10, valuation=6),
        ),
        E2RArchetype.AI_DRUG_DISCOVERY_PLATFORM: ArchetypeDefinition(
            archetype=E2RArchetype.AI_DRUG_DISCOVERY_PLATFORM,
            stage1_radar_signals=("AI drug discovery partnership", "candidate molecule", "platform milestone"),
            stage2_candidate_signals=("big pharma milestone", "clinical entry", "cash runway"),
            stage3_high_conviction_signals=("commercial or royalty path", "validated pipeline", "cash burn controlled"),
            stage4a_ongoing_signals=("pipeline advances with partner funding",),
            stage4b_graduation_overheat_signals=("AI platform label crowded", "valuation before clinical proof"),
            stage4c_thesis_break_signals=("clinical failure", "cash burn", "platform hype unwind"),
            key_evidence_families=("news", "research_report", "disclosure"),
            false_positive_patterns=("PoC treated as drug approval", "AI label without economics"),
            preferred_score_weights=_weights(eps_fcf=6, visibility=10, bottleneck=7, mispricing=12, valuation=6),
        ),
        E2RArchetype.DIGITAL_HEALTHCARE_AI: ArchetypeDefinition(
            archetype=E2RArchetype.DIGITAL_HEALTHCARE_AI,
            stage1_radar_signals=("clinical AI paper", "regulatory clearance", "hospital pilot"),
            stage2_candidate_signals=("hospital adoption", "reimbursement", "paid workflow", "recurring revenue"),
            stage3_high_conviction_signals=("workflow embedded", "recurring revenue", "OP improvement", "liability risk low"),
            stage4a_ongoing_signals=("hospital usage expands", "reimbursement remains intact"),
            stage4b_graduation_overheat_signals=("AI healthcare narrative crowded", "paper-only valuation premium"),
            stage4c_thesis_break_signals=("subgroup performance issue", "reimbursement denial", "liability event"),
            key_evidence_families=("research_report", "news", "financial_actual"),
            false_positive_patterns=("AUC headline without adoption", "pilot without revenue", "bias risk ignored"),
            preferred_score_weights=_weights(eps_fcf=18, visibility=17, bottleneck=8, mispricing=13, valuation=12),
        ),
        E2RArchetype.MEDICAL_AI_SUBGROUP_GENERALIZATION_RISK: ArchetypeDefinition(
            archetype=E2RArchetype.MEDICAL_AI_SUBGROUP_GENERALIZATION_RISK,
            stage1_radar_signals=("subgroup performance risk", "dataset bias", "liability risk"),
            stage2_candidate_signals=("risk event detected",),
            stage3_high_conviction_signals=("not a Green source; overlay only"),
            stage4a_ongoing_signals=("subgroup performance remains clean",),
            stage4b_graduation_overheat_signals=("AI paper valuation ignores subgroup weakness",),
            stage4c_thesis_break_signals=("subgroup performance issue", "dataset bias", "reimbursement absent", "liability event"),
            key_evidence_families=("research_report", "news", "financial_actual"),
            false_positive_patterns=("aggregate AUC treated as deployment proof", "bias risk ignored"),
            preferred_score_weights=_weights(eps_fcf=0, visibility=0, bottleneck=0, mispricing=0, valuation=0),
        ),
        E2RArchetype.MEDICAL_DEVICE_HEALTHCARE_EXPORT: ArchetypeDefinition(
            archetype=E2RArchetype.MEDICAL_DEVICE_HEALTHCARE_EXPORT,
            stage1_radar_signals=("medical device export growth", "new approval", "procedure growth"),
            stage2_candidate_signals=("repeat consumable revenue", "export channel", "OPM/ROE improvement"),
            stage3_high_conviction_signals=("recurring procedure demand", "ASP stable", "FCF improvement"),
            stage4a_ongoing_signals=("export channel and procedures remain strong",),
            stage4b_graduation_overheat_signals=("medical-device premium crowded", "target multiples saturated"),
            stage4c_thesis_break_signals=("approval delay", "safety issue", "price control", "channel failure"),
            key_evidence_families=("financial_actual", "research_report", "news"),
            false_positive_patterns=("one-time device sale", "approval without channel", "safety risk ignored"),
            preferred_score_weights=_weights(eps_fcf=20, visibility=22, bottleneck=13, mispricing=14, valuation=12),
        ),
        E2RArchetype.SURGICAL_ROBOT_GLP1_PROCEDURE_MIX_OVERLAY: ArchetypeDefinition(
            archetype=E2RArchetype.SURGICAL_ROBOT_GLP1_PROCEDURE_MIX_OVERLAY,
            stage1_radar_signals=("GLP-1 procedure impact", "bariatric slowdown", "procedure mix shift"),
            stage2_candidate_signals=("risk event detected",),
            stage3_high_conviction_signals=("not a Green source; overlay only"),
            stage4a_ongoing_signals=("procedure mix and consumables remain resilient",),
            stage4b_graduation_overheat_signals=("installed-base premium ignores procedure mix pressure",),
            stage4c_thesis_break_signals=("bariatric slowdown", "procedure mix worse", "system placement slowdown", "hospital capex cut"),
            key_evidence_families=("financial_actual", "news", "research_report"),
            false_positive_patterns=("installed base treated as revenue while procedures shift away",),
            preferred_score_weights=_weights(eps_fcf=0, visibility=0, bottleneck=0, mispricing=0, valuation=0),
        ),
    }
)


def archetype_definition(archetype: E2RArchetype | str) -> ArchetypeDefinition:
    """Return the definition for an archetype."""

    if not isinstance(archetype, E2RArchetype):
        archetype = E2RArchetype(str(archetype))
    return ARCHETYPE_DEFINITIONS[archetype]


def all_archetype_definitions() -> tuple[ArchetypeDefinition, ...]:
    """Return definitions for all archetypes."""

    return tuple(ARCHETYPE_DEFINITIONS[item] for item in E2RArchetype)


POSITIVE_GROUPS = frozenset({"structural_success", "success_candidate", "cyclical_success"})
COUNTEREXAMPLE_GROUPS = frozenset(
    {"one_off", "boom_bust", "overheat", "failed_rerating", "event_premium", "4b_watch", "4c_thesis_break"}
)


__all__ = [
    "ARCHETYPE_DEFINITIONS",
    "COUNTEREXAMPLE_GROUPS",
    "POSITIVE_GROUPS",
    "ArchetypeDefinition",
    "E2RArchetype",
    "all_archetype_definitions",
    "archetype_definition",
]
